{100}{}{Vedi un mercante.}
{101}{}{Vedi un vecchio mercante.}
{200}{}{Ehila', viaggiatore. Mi chiamo Bill. Cosa posso fare per te?}
{201}{}{Bentornato. Hai bisogno di qualcos'altro?}
{202}{}{Barattiamo.}
{203}{}{Ho saputo che sei la persona giusta con la quale parlare riguardo le carovane.}
{204}{}{Lasciamo perdere. Ci vediamo.}
{210}{}{Senti, ho notato che qui all'Abbazia e' stata raccolta molta attrezzatura e molti oggetti vecchi.
Non e' che hai trovato qualcosa di... speciale, durante il tuo tempo qui?}
{211}{}{Eh, l'hai notato, eh? Si', la gente dell'Abbazia ha una certa fascinazione per qualsiasi cosa pre-guerra,
specialmente se e' legata alla tecnologia. Si sono formati una specie di strana religione attorno ad essa. Non la capisco del tutto,
io, ma sono brave persone e pagano bene per qualsiasi cosa pre-guerra riesca a mettere le mani. Ma comunque,
per quanto riguarda qualcosa di speciale... hmm, [Lancia un'occhiata a Marcus.] E' strano che tu lo chieda, potrei proprio avere qualcosa che
interesserebbe al tuo amico qui.}
{212}{}{Eh, l'hai notato, eh? Si', la gente dell'Abbazia ha una certa fascinazione per qualsiasi cosa pre-guerra,
specialmente se e' legata alla tecnologia. Si sono formati una specie di strana religione attorno ad essa. Non la capisco del tutto,
io, ma sono brave persone e pagano bene per qualsiasi cosa pre-guerra riesca a mettere le mani. Ma comunque,
per quanto riguarda qualcosa di speciale... hmm, [Lancia uno sguardo al tuo gruppo.] Mi dispiace, non credo di avere nulla di speciale che
potresti trovare utile al momento.}
{213}{}{Davvero? Vediamo cos'hai da vendermi.}
{214}{}{Grazie. Lascia che ti chieda qualcos'altro.}
{215}{}{Ovvero?}
{216}{}{Vedete, non molto tempo fa e' passata di qui una carovana, che diceva di venire dal profondo sud. Dissero di essere
stati attaccati da alcuni di quei vili mutanti (rivolgendosi a Marcus) niente di personale, amico. Comunque, si vantarono molto di come
avevano fatto fuori tutti i muties. Sostenevano che fossero stati quasi una dozzina, e io dissi una stronzata. Ma si e' scoperto
che avevano delle prove.}
{217}{}{Si? Cos'era?}
{218}{}{Un'armatura da mutante massiccia che erano riusciti a recuperare da uno dei cadaveri. Per quanto ne so, potrebbe
essere stata rubata dalle ossa di qualche mutante morto da tempo che avevano trovato per caso nelle terre desolate, ma chi lo sa? Comunque, non
erano molto entusiasti di continuare a trascinarsi dietro quella cosa pesante, quindi me la offrirono per quattro soldi. Non sapevo cosa farmene
con essa, ma pensai che un affare e' un affare.}
{219}{}{Beh, sono sicuro che Marcus potrebbe trarne vantaggio. Quanto vuoi per essa?}
{220}{}{Interessante. Beh, Marcus e' già abbastanza duro. Non credo che avremo bisogno di quell'oggetto. Lasciami chiedere
un'altra cosa.}
{221}{}{Beh, questo bestione potrebbe facilmente essere fuso per fare tre o quattro set di armatura metallica. Diciamo 3000$.}
{222}{}{Ne ho avuto abbastanza.}
{223}{}{Non credo di volerla subito. Lasci che ti chieda qualcos'altro.}
{224}{}{Bene allora. Ci vorranno due persone per spostare questa cosa, quindi lasciami aiutarti ad adattarla al tuo amico qui.}
{225}{}{[Fatto]}
{226}{}{Ehi, si adatta perfettamente!}
{300}{}{Potrei sapere una cosa o due. Cosa ti piacerebbe sapere?}
{301}{}{Quanto spesso vieni rifornito?}
{302}{}{Le carovane cercano qualcuno da assumere?}
{303}{}{Ripensandoci, devo andarmene.}
{304}{}{Ricevo una nuova spedizione di rifornimenti due volte al mese. Francamente, vorrei che arrivassero più spesso, ma siamo solo su una rotta commerciale minore quindi immagino che questo sia il meglio che possiamo ottenere.}
{305}{}{Non ne sono del tutto sicuro. Di solito, quelli che passano da qui sono ben equipaggiati e non sono molto interessati a
fermarsi a lungo. Ma se stai cercando di unirti a uno di loro, ti dirigerei verso Redding o anche giù verso NCR.
Hanno carovane piuttosto attive e il buon aiuto e' sempre ricercato.}
{306}{}{Interessante. Ero curioso riguardo altro.}
{307}{}{Grazie. Barattiamo.}
{308}{}{Beh, grazie dell'informazione. Ci vediamo.}
{400}{}{Trovato qualcosa che ti serviva?}
{401}{}{Veramente, mi piacerebbe dare un'altra occhiata alla tua merce.}
{402}{}{Si' l'ho fatto. Ci vediamo.}
