{100}{}{Vedi una suora corpulenta.}
{101}{}{Vedi Elaine.}
{102}{}{Vedi sempre una guardia.}
{200}{}{Saluti!}
{201}{}{Ciao, qual e' il tuo nome?}
{202}{}{Cosa puoi dirmi a proposito dell'Abazia?}
{203}{}{Addio.}
{300}{}{Se vuoi sapere di più sul nostro ordine, parla con l'Abate. Puoi trovarlo nei suoi alloggi al terzo piano.}
{301}{}{Capisco. Ancora un paio di domande...}
{400}{}{Certo. Cos'altro vuoi sapere?}
{401}{}{Qual e' il tuo nome?}
{402}{}{Non proprio. Arrivederci.}
{403}{}{Cosa puoi dirmi a proposito dell'Abazia?}
{500}{}{Il mio nome e' Elaine.}
{501}{}{Capisco. Ancora un paio di domande...}
{600}{}{Ehi! Prima che tu vada, forse potresti farmi un favore. Dovrei portare questo pezzo di macchina a Max nella
sala copie al piano interrato. Ma vedi, il mio ginocchio sinistro mi ha dato fastidio ultimamente, ed e' davvero una seccatura per me salire e scendere
tutte quelle scale. Ti disturberebbe troppo portarglielo?}
{601}{}{Bene.}
{602}{}{Scusa, ma non ho tempo per chiacchierare. Ciao.}
{603}{}{Sembro forse il tuo servizio di consegna personale? Fallo tu stesso, grassa pigra stronza. Addio.}
{604}{}{Grazie! Ecco il pezzo. La sala copie e' al piano interrato. Usa semplicemente le scale direttamente dietro Fratello
Matthew nell'area della cappella.}
{605}{}{Nessun problema. [Prendi il pezzo.] Lo portero' da Max immediatamente.}
{700}{}{Me }
{701}{}{. Chi tu?}
{710}{}{Hehe. Bel nome.}
{711}{}{Ciao!}
{720}{}{Sei proprio un bravo ragazzone, vero? Potresti farmi un GRANDE favore ed essere il mio aiutante speciale oggi?}
{721}{}{Sei proprio una ragazzina speciale, vero? Potresti farmi un GRANDE favore ed essere la mia aiutante speciale oggi?}
{722}{}{Io speciale. Io aiutare.}
{723}{}{Io no aiutare.}
{730}{}{Davvero? Bene! Per favore porta questo pezzo a Max nella stanza delle copie. Lo puoi trovare nel SEMINTERRATO. Okay?}
{731}{}{Non ti deludero'!}
{740}{}{Devi allenarti di piu'.}
