{100}{}{Vedi una guardia tosta.}
{101}{}{Vedi una guardia dai muscoli imponenti, ma anziana, con la pelle bruciata dal sole. Dev'essere stato qualcosa di notevole
nel suo periodo migliore. Il suo sguardo penetrante sembra seguirti ovunque.}
{200}{}{Fatti gli affari tuoi rispettando la legge, straniero, e non ci saranno guai.}
{201}{}{Ti sto tenendo d'occhio, schiavista. Una mossa sbagliata e contaminerai il nostro cimitero per il resto dell'eternità.
Non te lo augurerei, e sono abbastanza sicuro che neanche tu lo gradirebbe, quindi non farti venire strane idee in quel
cervello contorto che hai.}
{202}{}{Chi sei?}
{203}{}{Dove posso trovare dei medicinali?}
{204}{}{Qualcuno sta dissotterrando le tombe, perche' non fai nulla al riguardo?}
{205}{}{Ho sentito qualcosa riguardo ad animali nel seminterrato. Ne sai qualcosa?}
{206}{}{Penso che sia ora di mandarti nella tomba. Balliamo, vecchio.}
{207}{}{Non importa. Arrivederci.}
{300}{}{Nessuno... Solo un vecchio guardia carovane in pensione. Molte persone mi scambiano per una specie di sceriffo perché sono
la cosa più simile alla legge da queste parti, ma non lo sono. Mi prendo semplicemente cura di questa comunità perché penso
che valga la pena proteggerla.}
{301}{}{E in cambio la comunità si prende cura di me. Ricevo un po' di alcol in omaggio dai monaci, Peterson si assicura
che io sia nutrito e Bill si assicura che abbia munizioni e stim. Non un brutto lavoro da pensionato, se me lo chiedi.}
{302}{}{Sono io quello che ti tiene in riga, e questo è tutto quello che devi sapere. Ora occupati dei fatti tuoi e lasciami
in pace.}
{303}{}{E' un bel accordo. Lasciami chiedere un'altra cosa.}
{304}{}{Comunque, arrivederci.}
{305}{}{Pensi di potermi tenere in riga? Vediamo se ci riesci, vecchio. Questo dovrebbe essere divertente.}
{400}{}{Puoi trovare Bill, il nostro commerciante residente, nell'edificio di fronte a qui. Per il resto, dovresti andare
da Percy's Survival Gear Locker al Junkyard di Gecko o da Happy Harry's nel Cortile di Vault City.}
{401}{}{Buono a sapersi. Ho un'altra domanda.}
{402}{}{Grazie, arrivederci.}
{500}{}{Se qualcuno è abbastanza povero o avido da cercare di dissotterrare le tombe, sono affari suoi. Non è che i morti possano
usare ciò con cui sono sepolti comunque. Non è un mio problema... Non ci perdo il sonno.}
{501}{}{Lascia che ti chieda qualcos'altro.}
{502}{}{Addio.}
{600}{}{Sì, e Fratello Thomas è scomparso. Era un uomo intelligente, ma un po' avventato. Non so cosa ci sia laggiù,
ma non credo che siano solo un mucchio di ratti e radscorpioni.}
{601}{}{Sì, e Fratello Thomas è scomparso. Non so cosa ci sia laggiù, ma non credo che siano solo un mucchio di ratti
e radscorpioni. Perché non lo scopri tu, duro?}
{602}{}{Allora perche' non vai a guardare tu stesso?}
{603}{}{Sei il duro della situazione, vero? Perché non trascini il tuo culo laggiù?}
{610}{}{È un po' imbarazzante, ma dopo aver trascorso così tanto tempo all'aperto con le carovane, mi innervosisco molto quando
vado sottoterra. Le pareti mi si chiudono addosso e ho difficoltà a respirare... Forse puoi scoprire cosa è successo a
Fratello Thomas?}
{611}{}{Vedro' di fare del mio meglio. Prima, pero', lascia che ti chieda qualcos'altro.}
{612}{}{Addio.}
{613}{}{Sono un duro, ed è per questo che ti spaccerò la faccia.}
{700}{}{Cos'altro vuoi sapere?}
{800}{}{E' bello rivederti.}
{801}{}{Ti sto tenendo d'occhio.}
