{100}{}{Vedi Jack, il medico dell'Abbazia.}
{101}{}{Ha una croce rossa sulla spalla.}
{200}{}{Se sei ferito, parla con me.}
{300}{}{Come posso aiutarti?}
{301}{}{Sono ferito. Puoi aiutarmi?}
{302}{}{[sbava]}
{303}{}{Allora, cosa fai qui all'Abbazia?}
{304}{}{Addio.}
{400}{}{E' fatto!}
{401}{}{Grazie.}
{402}{}{Smettila!}
{403}{}{[CONTINUA]}
{404}{}{[VIA]}
{405}{}{SMETTILA! SMETTILA! SMETTILA!}
{406}{}{[CONTINUA]}
{407}{}{[STOP]}
{408}{}{(All’improvviso, Jack comincia a sciogliersi.) MI STO SCI-OOO-GLIENDO, MI STO SCI-OOO-GLIENDO, OH CHE MONDO…}
{409}{}{Che diavolo...}
{500}{}{Ehi, non rubare le mie forniture mediche!}
{501}{}{Ottieni %d punti esperienza per aver fatto sciogliere Jack. Sei contento adesso, povero malato?}
{600}{}{Sono un dottore. Mi prendo cura della gente dell’Abbazia da… oh, saranno quindici anni ormai, credo.}
{601}{}{Capisco. Sono molti anni per studiare tutti i libri di medicina pre?bellici nella biblioteca dell’Abbazia. Devi essere davvero un ottimo dottore.}
{602}{}{Da dove hai preso tutto il tuo equipaggiamento medico?}
{603}{}{Interessante. Credo che me ne andro' ora.}
{604}{}{(Aggrugisce la fronte.) Mi considero un buon dottore, ma non posso certo dare il merito ai libri, visto che non mi è nemmeno permesso… lasciamo stare, non voglio parlarne. Mio padre era un dottore, ed e' stato lui a trasmettermi tutto cio' che so.}
{605}{}{Ah, capisco.}
{700}{}{Alcuni di questi medicinali li ho ricevuti da mio padre. La maggior parte degli altri era gia' qui all’Abbazia.}
{701}{}{Interessante. Ci vediamo.}
{702}{}{Pensi di potermi dare un po' delle tue medicine? Sembri averne in abbondanza.}
{703}{}{Vuoi che te le dia cosi', senza niente in cambio? Cosa ti fa pensare di meritarle piu' della gente dell'Abbazia?}
{704}{}{Perche' tendo a farmi male... spesso.}
{705}{}{Perche' sono in una missione sacra per trovare un Garden of Eden Creation Kit. Capisci, tutto il mio villaggio morira' se non trovo questo dispositivo in tempo. La tua gente, invece, sembra vivere una vita tranquilla, senza grande bisogno di cosi' tante medicine. Non ti sto chiedendo molto, anche la quantita' piu' piccola che puoi darmi mi aiuterebbe enormemente.}
{706}{}{[Riflette un momento sulle tue parole, poi annuisce.] Va bene, ti daro' un po' delle nostre scorte mediche in eccesso. Sembra che te ne serviranno. Tieni.
[Te le porge.] Buona fortuna, viandante.}
{707}{}{Grazie, Jack. Sei un vero salvatore delle Lande. Arrivederci.}
{708}{}{Allora forse dovresti imparare a stare piu' attento. Mi dispiace, ma non ho intenzione di regalare cosi' le scorte mediche dell'Abbazia.}
{709}{}{D'accordo. Addio.}
{800}{}{Adesso non posso parlare.}
{801}{}{Scusa, sono nel mezzo di qualcosa ora. Vieni a trovarmi piu' tardi.}
{802}{}{Ciao.}
