{100}{}{Vedi una guardia.}
{101}{}{Vedi una guardia che indossa una Power-Armor.}
{102}{}{Vedi una persona che indossa una Power-Armor dall'aspetto insolito. Sul petto c'e' uno stemma che non ti e' familiare.}
{103}{}{Niente da segnalare.}
{104}{}{Qui non succede nulla... li' da te, invece?}
{105}{}{Perche' non sei al tuo posto, soldato? Non dovresti gironzolare da queste parti.}
{106}{}{Sei senza uniforme.}
{107}{}{Faresti meglio a presentarti dal Sergente e a vestirti.}
{108}{}{Stai prendendo un grosso rischio a girare senza armatura. Faresti meglio a presentarti all'armeria.}
{109}{}{Chi diavolo...? Allarme! Intrusi!}
{110}{}{Intrusi nel settore! Allarme!}
{111}{}{Intrusi multipli! Suonate l'allarme!}
{112}{}{Allarme sicurezza! Sigillate la base!}
{113}{}{Chiudete tutte le postazioni! Allarme!}
{114}{}{Allarme intruso! Codice rosso!}
{115}{}{Ti schiacceremo!}
{116}{}{L'Enclave dominera' il mondo!}
{117}{}{Perche' l'Enclave viva, tu devi morire!}
{200}{}{...stronzo...}
{201}{}{...si', fai BENE ad andartene...}
{202}{}{...Giovane Marmotta dei miei stivali...}
{203}{}{...si', signore! Fottiti, signore!...}
{300}{}{Aspetta un attimo. Cosa pensi di fare con quel vertibird? Non c'e' nessun volo in programma nei prossimi giorni.}
{301}{}{Nrg?}
{302}{}{Lo so.}
{303}{}{Ah, scusa. Stavo solo dando un'occhiata. Me ne vado subito.}
{304}{}{C'e' stato un cambio di programma. Questo lo prendo io.}
{310}{}{Come? Oh, capisco. Guardare, ma non toccare. Okay? Toccalo un'altra volta e sei morto.}
{311}{}{(Sorridi poi attacca.)}
{312}{}{(Allontanati.)}
{315}{}{Oh, merda! Abbiamo un intruso. Codice Rosso! Ripeto, Codice Rosso!}
{316}{}{Davvero un'ottima idea. Tocca di nuovo il vertibird e ti pianto una pallottola in mezzo agli occhi.}
{320}{}{Certo. E quindi tu sei...}
{321}{}{...Intenzionato a lasciarti in pace. Scusa il disturbo.}
{322}{}{...Incaricato di portare un messaggio importante al quartier generale.}
{323}{}{Oh, davvero? E cosa dice questo messaggio?}
{324}{}{E' super top secret. Non posso dirtelo.}
{325}{}{Te lo diro', ma e' di vitale importanza che tu non comunichi tale informazione a nessun altro, o scatenerai il panico. Mi e' giunta notizia che uno degli schiavi dell'ultimo carico era infetto. Si tratterebbe di un virus sconosciuto e letale. *Devo* raggiungere la base immediatamente, o saremo tutti spacciati. Adesso piantala di farmi perdere tempo... non c'e' un secondo da perdere.}
{326}{}{E tu speri che me la beva? Sembra proprio che abbiamo un intruso tra noi...}
{327}{}{Diamine! Ah, pazienza. Qua dentro non mi dice mai nulla nessuno. D'accordo. Vai pure.}
{328}{}{Woah, sembra piuttosto grave. Farai meglio ad andare subito. Questa patata bollente te la lascio volentieri. Oh, e non temere: non diro' nulla a nessuno.}
{329}{}{[FATTO]}
{400}{}{[Dopo mezz'ora seduto nel buio della stiva, senti il velivolo toccare terra di nuovo. Un attimo dopo, il portellone si apre e vedi una squadra di soldati in armatura potenziata. 
Uno di loro ti guarda due volte, poi si gira verso gli altri.] Merda! Uno di quei mutanti della Landa si e' nascosto nel 'bird! ALLERTA! Abbiamo un intruso!}
{401}{}{[Dopo mezz'ora seduto nel buio della stiva, senti il velivolo toccare terra di nuovo. Un attimo dopo, il portellone si apre e vedi una squadra di soldati in armatura potenziata. 
Uno di loro ti guarda due volte, poi si gira verso gli altri.] Merda! Alcuni di quei mutanti della Landa si sono nascosti nel 'bird! ALLERTA! Abbiamo degli intrusi!}
{402}{}{[Salta fuori e vedi quanti riesci a buttar giu' prima che ti facciano fuori.]}
{403}{}{[Alza le mani in segno di resa e spera nel meglio.]}
{410}{}{Oh, sembra che il mutante non voglia combattere. Forse dovremmo portarlo dal Comandante, vedere cosa vuole farne.}
{411}{}{Oh, sembra che la mutante non voglia combattere. Forse dovremmo portarla dal Comandante, vedere cosa vuole farne.}
{412}{}{Oh, sembra che i mutanti non vogliano combattere. Forse dovremmo portarli dal Comandante, vedere cosa vuole farne.}
{420}{}{[Dopo mezz'ora seduto nel buio della stiva, senti il velivolo toccare terra di nuovo. Un attimo dopo, il portellone si apre e vedi una squadra di soldati dell'Enclave. 
Uno di loro ti guarda due volte.] Che diavolo ci fai qui dietro? Non eri autorizzato a essere in quella missione. Come ti chiami, soldato?}
{421}{}{Il mio nome non importa, perche' non sono qui per parlare. [Salta fuori e inizia a combattere.]}
{422}{}{Io? Oh, sono, uh, *coff*mumble*coff*. Non badare a me. Anzi, forse dovrei andare. [Esci e prova ad allontanarti con noncuranza.]}
{423}{}{Il mio nome e' }
{424}{}{. Dove sono?}
{425}{}{No, qual e' il *tuo* nome, soldato? Sono stato messo qui per testarti e devo dire che hai FALLITO. Se fossi un assassino suicida della Landa, tu e tutta la tua squadra sareste morti adesso! Inaccettabile! Datti una regolata, soldato!}
{426}{}{Uh . . . il mio nome }
{427}{}{. Io fare giro divertente su uccellino di metallo! Andare ancora! Voglio andare ancora!}
{428}{}{Tu non serve sapere mio nome. Io non ti piace. Io uccido. [Salta fuori e inizia a combattere.]}
{430}{}{Che sei, ubriaco? Sei a Navarro, ovviamente. Se hai problemi di memoria, soldato, forse dovresti farti controllare. Magari un po' di quella radiazione la' fuori ti ha colpito.}
{440}{}{Non dirmi stronzate. Sei una delle nuove reclute, vero? Heh. Quella tua linguaccia ti mettera' nei guai, e non vedo l'ora di vederlo. Ora torna al tuo posto, soldato.}
{450}{}{Signorsi', signore!}
{451}{}{Si', signora!}
{460}{}{[Il soldato guarda uno dei suoi compagni.] Mio Dio, il contatto con tutti quei mutanti e la radiazione deve averlo rincoglionito. Vedi? *Ecco* perche' non mi offro mai volontario per quelle missioni nella Landa. Comunque, togliamo questo idiota dalla sua miseria prima che ci contamini.}
{461}{}{[Il soldato guarda uno dei suoi compagni.] Mio Dio, il contatto con tutti quei mutanti e la radiazione deve averla rincoglionita. Vedi? *Ecco* perche' non mi offro mai volontario per quelle missioni nella Landa. Comunque, togliamo questa idiota dalla sua miseria prima che ci contamini.}
