{100}{}{Vedi un ragazzino.}
{101}{}{Vedi il piccolo Bobby.}
{102}{}{Indossa vestiti sporchi e ha lividi sul collo e sul viso.}
{103}{}{Indossa dei vestiti nuovi e ha un sorriso in faccia.}
{104}{}{Ciao signore! Mi chiamo Bobby e vivo qui con mio papa'.}
{105}{}{Ciao signora! Mi chiamo Bobby e vivo qui con mio papa'.}
{106}{}{Capisco. Beh, gra-}
{107}{}{Sei qui perche' mio papa' ti deve dei soldi? Non so se e' qui o no. Ma se sapessi dov'e',
 te lo direi, perche' magari lo picchieresti cosi' forte da non farlo tornare mai piu' a casa.}
{108}{}{E' terribile, Bobby. Tuo padre non ha il diritto di trattarti cosi' -- nessun genitore ce l'ha.}
{109}{}{Ah! Picchierei anche mio figlio se non mi ascoltasse. Tuo padre sembra un brav'uomo.}
{110}{}{[Gli si illuminano gli occhi.] Non sei come gli altri che passano di qui. Mi piaci. [Sospira forte.]
 Vorrei che mio papa' fosse piu' come te. A volte penso di scappare. Alcuni miei amici non hanno una casa, e dicono
 che non e' poi cosi' male. Finche' portano abbastanza cose a Mr. Flick, possono mangiare una volta al giorno. Ma Mr. Flick non sembra molto
 gentile nemmeno lui -- anzi, sembra proprio come mio papa'.}
{111}{}{Sei cattivo! Vai via. Non mi piaci.}
{112}{}{Ci deve essere qualcosa che si puo' fare. Ti viene in mente qualche adulto in questa citta' disposto a
 occuparsi di te -- o di questi bambini senzatetto?}
{113}{}{[Bobby scrolla le spalle.] Forse Mom? Non intendo *mia* mamma -- la mia e' morta -- ma c'e' una signora che tutti chiamano Mom. Non so perche'.
 Forse perche' e' molto gentile? Ha una tavola calda dall'altra parte della citta'. [Indica a nord-est.] I miei amici senzatetto vanno
 li' e lei gli passa del cibo gratis di nascosto. Vorrei che papa' mi portasse li', perche' lei sa rendere il ratto davvero buono!}
{114}{}{Hmm, ho *un po'* di fame. Forse andro' a fare visita a Mom. Stammi bene, Bobby.}
{115}{}{Sei proprio un moccioso. Meglio che me ne vada prima di riempirti di botte. Ciao.}
{116}{}{Indovina, Bobby? Ho parlato con Mom, e aprira' una bella casa grande dove tu e tutti i tuoi amici senzatetto
 potrete andare a vivere insieme. Sara' nel grande edificio proprio dall'altra parte della strada.
 Ha detto che sara' tutto pronto in un paio di giorni.}
{117}{}{[Un enorme sorriso illumina il volto del ragazzo.] Davvero? Fantastico! [Ti abbraccia.] Non vedo l'ora di vivere li' con tutti i miei
 amici! Sono cosi' felice! Grazie ancora signore, sei il migliore!}
{118}{}{[Un enorme sorriso illumina il volto del ragazzo.] Davvero? Fantastico! [Ti abbraccia.] Non vedo l'ora di vivere li' con tutti i miei
 amici! Sono cosi' felice! Grazie ancora signora, sei la migliore!}
{119}{}{Di niente, ragazzo. Ci vediamo.}
{120}{}{Ciao di nuovo! Hai parlato con la signora Mom?}
{121}{}{Non preoccuparti, Bobby, ci sto lavorando.}
{122}{}{Aiuti Bobby a trovare una vita migliore.}
{123}{}{Ciao di nuovo! Grazie di tutto. Adoro questo nuovo posto. Mom e' davvero una grande donna!}
{124}{}{Adoro questo nuovo posto. Mom e' davvero una grande donna!}
{125}{}{Sono cosi' emozionato! E' ora di preparare le mie cose.}
{126}{}{Mi chiedo se papà si accorgerà che sono sparito.}
{127}{}{Andrà molto meglio così.}
{200}{}{Non mi piaci. Vai via!}
{210}{}{Sembra che tuo padre non ti piaccia molto. Posso chiederti perche'?}
{211}{}{Moccioso, chi ti credi di essere per parlare cosi' di tuo padre?}
{220}{}{Perche' il mio papa' non e' molto gentile. Mi lascia sempre da solo a casa, e quando *c'e'* e' sempre ubriaco oppure
 dice che sta volando con il Jet, che e' una bugia perche' non lo vedo mai volare da nessuna parte. A volte porta
 a casa una fidanzata -- ne ha tante -- e mi fa uscire per un po', anche se e' notte fonda
 e fa freddo o piove.}
{221}{}{E'-}
{230}{}{Oh! E a volte mi dice di prendere di nascosto delle cose alla gente. Dice che e' un gioco e che poi le restituisce,
 ma non gli credo. Ma se non lo faccio, allora si arrabbia davvero e i suoi occhi diventano spaventosi, e mi fa male.
 Vedi? [Alza la manica, mostrando un brutto livido sul braccio.]}
