{100}{}{Vedi una signora anziana dall'aspetto gentile.}
{150}{}{Vedi Mama, impegnata a cucinare e a pulire.}
{151}{}{Vedi una signora anziana, robusta e con un sorriso allegro sul viso.}
{200}{}{Ehila', io sono Mama. Non ti ho mai visto da queste parti, prima d'ora.}
{201}{}{Ciao. Cosa puo' fare Mama per te?}
{202}{}{Me }
{203}{}{Mmmm. Ook? Ciao ciao mammina.}
{220}{}{Hai fatto fuori praticamente meta' delle mie scorte. Perche' non ti trovi un altro posto dove andare a stare per un po'? Qui per oggi hai gia' mangiato abbastanza.}
{221}{}{Bene }
{222}{}{ hai davvero l'aria di essere una persona con una gran confusione in testa. Non sopporto di vedere soffrire una povera creatura. Vuoi qualcosa da mangiare?}
{223}{}{Me pieno. Cibo di Mama buono. Ciao Mama.}
{224}{}{Me paga?}
{225}{}{Me va. Ciao Mama.}
{240}{}{Beh, OK. Cos'hai? (Mama indica il tuo portamonete)}
{241}{}{Mama? (le porgi il portamonete)}
{242}{}{No! Me va. Ciao mammina.}
{250}{}{Veramente no. Mi dispiace. Abbiamo solo pasticcio di ratto, polpettone di ratto e spaghetti.}
{251}{}{Cosa vorresti mangiare, questa volta?}
{252}{}{Uh, potrei avere qualcosa che non contenga cosi' tanto ratto?}
{253}{}{Credo che prendero' il polpettone di ratto.}
{254}{}{Credo che prendero' il pasticcio di ratto.}
{270}{}{Puoi prendere gli spaghetti. Non c'e' molta carne di ratto, dentro - solo il sugo.}
{271}{}{Beh, OK, credo che prendero' gli spaghetti con sugo di ratto.}
{280}{}{Te ne porto subito una bella porzione. Sono 10$.}
{281}{}{Al momento non ho abbastanza soldi. Lascia che ti faccia qualche domanda, invece.}
{282}{}{10$ per un ratto? Devi essere pazza. Diamine, giu' al villaggio li facciamo pagare molto di piu'! Affare fatto.}
{283}{}{OK. Ecco i soldi.}
{284}{}{Credo di aver cambiato idea. Lascia che ti faccia qualche domanda, invece.}
{285}{}{Credo che tornero' piu' tardi. Ci vediamo.}
{300}{}{Avevi proprio una gran fame. Adoro vedere un giovane con un sano appetito. Ti puo' bastare?}
{301}{}{Proprio no, Mama. Voglio il secondo.}
{302}{}{Certamente. Lascia che ti chieda qualcosa, Mama.}
{303}{}{Per il momento basta cosi'. Arrivederci, Mama.}
{320}{}{Beh, avrei proprio bisogno che qualcuno consegnasse il pranzo a Smitty. Si trova ad ovest di qui, giu' al deposito rottami. Potresti farlo tu per me? Se lo farai ti offriro' un pasto gratuito.}
{321}{}{Certo, nessun problema.}
{322}{}{Devo pensarci su. Nel frattempo, lascia che ti chieda qualcos'altro.}
{323}{}{Uh, mi spiace, Mama. Non posso. Ci vediamo.}
{340}{}{Sei fortunato. Oggi serviamo stufato di radscorpioni.}
{341}{}{Oggi serviamo ratto-porco brasato.}
{342}{}{Oggi serviamo code di radscorpione al vapore, affogate nel burro.}
{343}{}{Tutto quel che ho, al momento, e' zuppa di cavoli.}
{344}{}{Frittelle di brahmin appena fatte!}
{345}{}{Il pasticcio di gecko alla brace e' quasi pronto.}
{346}{}{Filetto.}
{347}{}{Ratto-talpa ben cotto.}
{348}{}{Fluttuante in fricassea.}
{349}{}{Filetto mignon.}
{350}{}{Medaglioni di gecko alla griglia.}
{351}{}{Mantide al Marsala.}
{352}{}{Manicotti di ratto-talpa.}
{353}{}{Brahmin allo spiedo.}
{354}{}{Radscorpione en croute.}
{355}{}{E' Smeat!}
{356}{}{Uh, non ne sono sicura, ma sa un po' di pollo.}
{357}{}{Cosciotti di centauro, la mia specialita'.}
{358}{}{E' una sorpresa.}
{359}{}{Non posso rivelare le mie ricette segrete!}
{360}{}{Davvero?}
{375}{}{Ecco qua. Mi sembri mezzo morto di fame. (Mama ti serve un grande piatto fumante pieno di cibo dall'odore delizioso.)}
{376}{}{Grazie, Mama.}
{385}{}{Ecco fatto. Spero ti sia piaciuto.}
{386}{}{Mmm, yum yum. Ciao, Mama.}
{395}{}{Grazie mille. Lo farei da sola, ma non rimarrebbe nessuno a tener d'occhio il locale. Ecco il pranzo di Smitty. Se non glielo facessi portare, sono sicura che si dimenticherebbe persino di mangiare.}
{396}{}{Glielo porto subito.}
{405}{}{Mi hai davvero deluso. Il povero Smitty e' stato costretto a venire sin qui per mangiare. E adesso cosa vuoi?}
{406}{}{Ehila', io sono Mama e sono la proprietaria di questo locale. Qui serviamo il miglior cibo che si possa trovare a nord di New Reno.}
{407}{}{Di cosa vuoi parlare con Mama?}
{408}{}{Tu non sei la mia mamma.}
{409}{}{Hai mai sentito parlare di un Vault o di una persona di nome Vic?}
{410}{}{Cosa c'e' da fare, qui in citta'?}
{411}{}{Cos'avete da mangiare, qui?}
{417}{}{Oh, guarda chi c’e'… il mio eroe. Cosa puo' fare Mom per te oggi?}
{425}{}{Lo so. Ma qui tutti mi chiamano cosi'. Diamine, arrivo persino a trattare le persone come fossero miei figli - a patto che rispettino le mie regole.}
{426}{}{Regole?}
{435}{}{Esatto. Niente furti, bestemmie e risse - nel mio locale, no no no. Perche' se lo fai, fuori te ne andrai. A me piace la tranquillita'.}
{436}{}{Capisco. Lascia che ti chieda qualcos'altro.}
{437}{}{Mi pare giusto. Ci vediamo dopo, Mama.}
{445}{}{Beh, c'e' una Vault City un bel po' ad est di qui e un po' a nord. E Vic, hmm, fammi pensare...}
{446}{}{Spero tanto che tu sappia dove si trova Vic. E' un mercante.}
{447}{}{Grazie, ma questo e' tutto quello che mi serviva sapere. Ciao, Mama.}
{455}{}{Vic il mercante? Questo mi fa suonare una campanella in testa. Si', credo che Metzger lo tenga prigioniero per qualche motivo.}
{456}{}{Chi e' Metzger e dove posso trovarlo?}
{457}{}{Ottimo, Mama. Grazie.}
{465}{}{Metzger e' il capo della Gilda degli Schiavisti della zona. Ha un sacco di persone rinchiuse nel suo palazzo. E' all'inizio della strada, proprio a nord di qui.}
{466}{}{Metzger era a capo della Gilda degli Schiavisti della zona. Nel suo palazzo teneva rinchiuse molte persone. Ma non saprei dirti come vadano le cose adesso - ho sentito dire che e' stato ucciso.}
{467}{}{Grazie per l'informazione. Lascia che ti chieda qualcos'altro, Mama.}
{468}{}{Adesso dovrei andare ad occuparmi di alcune cose. Grazie, Mama.}
{475}{}{Sbrigati e porta subito il pranzo a Smitty.}
{476}{}{Non ti aiutero' finche' non avrai mantenuto la tua parola.}
{477}{}{Sbrigati.}
{478}{}{Va' a portare il pranzo a Smitty. Sbrigati.}
{479}{}{Smetti di grattarti la pancia e porta il pranzo a Smitty.}
{485}{}{Hai fatto un buon lavoro. E chissa' che appetito ti sara' venuto! La tua ricompensa e' una vera leccornia. Una combinazione di tutti i piatti che serviamo qui, preparata appositamente per te.}
{486}{}{Sembra ottima! Portamela subito!}
{487}{}{Gee, Mama. In questo momento non credo di voler mangiare, ma grazie lo stesso. Ci vediamo.}
{500}{}{Hmm, non ne so molto. Probabilmente qualcuno ha deciso di divertirsi un po', ecco tutto.}
{501}{}{E' sempre stata infestata?}
{502}{}{C'e' qualcuno che usa quella casa?}
{503}{}{Sono d'accordo. Ciao.}
{520}{}{Tutto e' cominciato circa 2 anni fa. Alcune persone iniziarono a dire di aver udito dei lamenti, di aver visto degli spiriti e altre sciocchezze del genere. Ma io non ci credo.}
{521}{}{Due anni, eh? Qualcuno usava la casa a quel tempo?}
{522}{}{Nemmeno io. Grazie.}
{540}{}{Uno dei ragazzi era solito dormire la', alcuni anni fa. Forse lui sa qualcosa.}
{541}{}{Chi e'?}
{542}{}{Probabilmente no. Ci vediamo.}
{560}{}{Veniva qui spesso a chiedermi di dargli qualche soldo in cambio di varie cose. Gioielli, soprattutto. Ricordo un piccolo medaglione d'oro che ha tenuto per se'.}
{561}{}{Ti ricordi il suo nome?}
{562}{}{Medaglione? Strano... Chi era?}
{563}{}{Lascia che ti chieda qualcos'altro.}
{564}{}{Grazie, arrivederci.}
{580}{}{Non sono sicura. Mi pare fosse Joseph, Joel o qualcosa del genere. Dovrebbe avere circa 19 anni... E' un vero peccato. Credo che adesso faccia parte di una banda di teppisti qui in citta'.}
{581}{}{Grazie. Ho un'altra domanda da farti.}
{582}{}{Grazie, arrivederci.}
{600}{}{Cosa sai a proposito della casa infestata?}
{800}{}{Ho notato che sembra ci siano molti orfani in giro per la citta'.}
{801}{}{E' un peccato, vero? Quei poveri bambini che vivono per strada cosi'... Molti di loro rubano per sopravvivere -- soprattutto da
 forestieri -- quindi se ne becchi uno che cerca di sfilarti qualcosa, abbi pieta' di loro. Non dico che sia
 giusto, ma e' un mondo duro quello in cui viviamo, e tutti facciamo quello che dobbiamo per arrivare a fine giornata.}
{802}{}{Deve esserci qualcosa che possiamo fare. Da quello che sento, sembri essere l'unica persona in giro che
 si preoccupi davvero di quei bambini.}
{803}{}{Certo che mi importa. I bambini sono il nostro futuro. Non *devono* per forza crescere per diventare drogati, delinquenti e prostitute come
 la maggior parte dei loro genitori inetti. Con un'istruzione e un po' d'amore e cura, questi bambini potrebbero diventare il tipo di
 gente perbene di cui abbiamo cosi' disperatamente bisogno in questo mondo. Ho provato a fondare un orfanotrofio per loro, ma purtroppo non e' andato in porto.}
{804}{}{Forse e' ora di riprovare. Non restera' in citta' ancora per molto, ma faro' quello che posso per aiutare finche' sono qui.}
{805}{}{Peccato. E' stato un piacere parlare con te. Ciao.}
{806}{}{Si', forse *potresti* aiutare. Vedi, ho procurato un grande edificio sul lato sud-ovest che, con un po' di lavoro, farebbe un ottimo
 orfanotrofio. Ma un branco di miserabili lo occupa abusivamente e si rifiuta di andarsene a meno che non paghi una cifra assurda. Anche se *avessi* i soldi, non li darei
 a quei bulli -- li userebbero solo per avvelenarsi ulteriormente. Andrei dalle autorita', ma purtroppo non esistono al Den.
 Forse avresti piu' fortuna a convincerli ad andarsene?}
{807}{}{Sono sicuro di poterli cacciare via. In un modo o nell'altro. Ti faro' sapere quando se ne sono andati.}
{808}{}{Non sono mai stato un fan dello sfrattare la gente. Forse qualcun altro e' piu' adatto per questo.}
{809}{}{Oh... capisco. E' davvero un peccato. Grazie comunque per aver provato. Vuoi qualcosa prima di andare?}
{810}{}{No. Ciao, Mom.}
{811}{}{Se beco uno di quei piccoli bastardi a rubarmi qualcosa, sara' l'ultima cosa che fanno. Non mi importa quale
 sia la loro scusa, un ladro e' un ladro. Ciao.}
{820}{}{Buone notizie, mamma. L'edificio e' tutto tuo. Ho incontrato un piccolo ostacolo, ma quegli occupanti abusivi non ti daranno piu' fastidio.}
{821}{}{Gli occupanti hanno detto che se ne andrebbero e che sono dispiaciuti per i problemi causati. Stanno attualmente pulendo il posto per cercare di rimediare. Pensavo che forse, se la cavano abbastanza bene, potresti offrire a qualcuno di loro un lavoro.}
{822}{}{Oh, che bella notizia! Grazie mille! Spero solo che nessuno si sia fatto male nel processo. Contattero' alcuni amici e inizieremo
 subito. Se sei ancora in citta' tra qualche giorno, dovresti passare. Speriamo di avere tutto operativo entro allora. Oh,
 sono cosi' emozionata! Grazie ancora. Ecco, questo pasto e' offerto da me.}
{823}{}{Hmm... suppongo che tutti meritino una seconda chance. Passero' la' con alcuni amici e ne parleremo con loro. Grazie mille
 per avermi aiutato con questo. Se sei ancora in citta' tra qualche giorno, dovresti passare. Speriamo di avere tutto operativo entro allora. Oh, sono cosi'
 emozionata! Grazie ancora. Ecco, questo pasto e' offerto da me.}
{824}{}{Grazie, Mom. Ci vediamo.}
{850}{}{Aiuti a fondare un orfanotrofio per i bambini del Den.}
{1821}{}{Buone notizie, mamma. L'edificio e' tutto tuo. Ci e' voluto un po' di convincimento, ma ho fatto accettare agli occupanti abusivi di fare i bagagli e andarsene.
 Non credo che ti daranno piu' fastidio.}
{1822}{}{Oh, che bella notizia! Grazie mille! Contattero' alcuni amici e inizieremo subito. Se sei ancora in citta' tra qualche giorno, dovresti passare.
 Speriamo di avere tutto operativo entro allora. Oh, sono cosi' emozionata! Grazie ancora. Ecco, questo pasto e' offerto da me.}
