{100}{}{Vedi un abitante del Den.}
{101}{}{Vedi un abitante del Den.}
{200}{}{Salve e benvenuto a- Ehi! Sei tu quello che ha aiutato a rendere possibile questo posto. La gente del Den apprezza davvero
 quello che hai fatto.}
{201}{}{E' stato un piacere. Come stanno i bambini?}
{202}{}{Stanno bene. Grazie a te, sono fuori dalle strade e ora hanno un posto dove vivere. Gli occupanti con cui hai trattato
 sono anche un grande aiuto qui. Grazie ancora per tutto!}
{203}{}{Stanno bene. Grazie a te, sono fuori dalle strade e ora hanno un posto dove vivere. Grazie ancora per tutto!}
{204}{}{Mi fa piacere. Stammi bene.}
{205}{}{Ciao di nuovo! Serve qualcosa?}
{206}{}{No, sto solo dando un'occhiata.}
