{100}{}{Vedi un ologramma dall'aspetto logoro.}
{101}{}{Vedi il Direttore della Manutenzione del Suolo.}
{102}{}{Ologramma 10031. E' responsabile della manutenzione dei terreni dell'EPA.}
{200}{}{Salve. Posso chiederti come hai fatto ad arrivare qui? Gli ascensori verso la superficie sono fuori uso da molto tempo.}
{201}{}{Vediamo... Ho usato una corda per scendere nel vano dell'ascensore fino al livello dei servizi... Poi ho strisciato attraverso un condotto di ventilazione e mi sono ritrovato in un'area di manutenzione dei robot...}
{210}{}{Sono sorpreso che tu sia passato oltre tutte quelle maledette piante senza essere mangiato. Sono l'Ologramma 10031, il Direttore della Manutenzione dei Terreni qui all'EPA. [Sospira profondamente.] Lo so, lo so, i terreni fanno schifo. Non serve che me lo dica tu.}
{211}{}{Se non ti piace come appaiono i terreni, perche' non fai qualcosa a riguardo?}
{212}{}{Non scherzo. I terreni sono pieni di melma radioattiva, cadaveri, piante carnivore mutanti... Sul serio, devi essere il peggior custode di terreni della storia.}
{220}{}{Se potessi fare qualcosa, credimi, lo farei. Non ho un corpo fisico, e quei maledetti robot non rispondono a una parola di quello che dico. Lavoro al 100% di inefficienza da decenni -- quanto e' patetico? Gli altri ologrammi non me lo fanno dimenticare. L'unico piu' inutile di me e' il Direttore delle Operazioni.}
{221}{}{Forse posso aiutare in qualche modo?}
{222}{}{E' davvero un peccato. Ora devo andare. Addio.}
{230}{}{Ehi, se sei davvero disposto ad aiutare, sarebbe fantastico. Mi assicuro che tu riceva qualcosa per il disturbo.}
{231}{}{Consideralo fatto. Come posso aiutarti?}
{232}{}{No, ora non ho tempo.}
{240}{}{Quelle piante di spore mutate si sono diffuse oltre la serra e hanno messo radici in tutti i terreni dell'EPA. Se potessi liberarmi di quei bastardi, sarebbe un grande passo nella direzione giusta.}
{241}{}{Certo, posso eliminare tutte le piante di spore per te. Tornero' quando avro' finito.}
{242}{}{E' stato facile. Li ho gia' uccisi tutti.}
{250}{}{Ciao di nuovo. Cosa posso fare per te? *Sospiro*}
{251}{}{Sembri piuttosto giù. Cosa c'e' che non va?}
{260}{}{Salve di nuovo. Hai ripensato ad aiutarmi? Come ho detto prima, ne varra' la pena per te.}
{261}{}{Sì, perché no. Non ho niente di meglio da fare.}
{262}{}{No, sono ancora troppo impegnato. Tornerò un'altra volta.}
{270}{}{Hai completato il compito per me?}
{271}{}{Si', ho eliminato tutte le piante. I terreni sembrano ancora un inferno, ma almeno ora sono un po' piu' sicuri.}
{272}{}{No, non ancora. Tornerò da te.}
{280}{}{Oh, grazie mille. Per questo, ti assumo ufficialmente come mio assistente custode dei terreni. [Indica una chiave sul pavimento ai suoi piedi.] Sono riuscito a convincere uno dei robot mezzi funzionanti a portartela. Ora hai l'autorizzazione per accedere al deposito. Grazie ancora.}
{281}{}{[Raccolgi la chiave e la metti in tasca.] Nessun problema. Ci si vede.}
{290}{}{Sembri piuttosto malconcio. Va tutto bene?}
{291}{}{Si', tutto bene. Ho avuto qualche problema con delle piante mutate scendendo qui, ma me ne sono occupato.}
{300}{}{Davvero? Meraviglioso! Per questo, ti assumo come mio assistente custode dei terreni. [Indica una chiave sul pavimento ai suoi piedi.] Sono riuscito a convincere uno dei robot mezzi funzionanti a portarmele tempo fa -- per sicurezza. Prendile. Ora hai l'autorizzazione per accedere al deposito. Grazie ancora.}
{301}{}{Oh no. Ho fatto tutto il possibile. Non preoccuparti.}
{302}{}{Grazie! Addio.}
{310}{}{Ehi, mi hai fatto un favore, quindi prendi la chiave e tutto cio' che vuoi o ti serve. E' il mio modo di ringraziarti per quello che hai fatto.}
{311}{}{Oh, va bene allora. Dimmi, chi sei esattamente? Perche' e' cosi' importante per te che io abbia eliminato tutte queste piante?}
{320}{}{Sono il Direttore della Manutenzione dei Terreni. Mi assicuro che i terreni siano in buono stato, ma essendo un ologramma non posso fare nulla da solo, quindi comando i robot per farlo al posto mio. Poiche' la maggior parte di loro ha smesso di funzionare, ho lavorato al 100% di inefficienza negli ultimi anni. Mi hai aiutato piu' di quanto tu possa immaginare.}
{321}{}{Bene, nessun problema. Ora devo andare.}
{330}{}{Continua così, assistente.}
{331}{}{Ora sto lavorando all'1% di efficienza!}
{332}{}{Hai eliminato le piante mutanti che infestavano i terreni dell'EPA.}
{333}{}{L'intero posto e' stato invaso da queste piante mutanti.}
{334}{}{Sono dappertutto.}
{335}{}{E poi ci sono le mantidi...}
{336}{}{La serra è a pezzi.}
{337}{}{Se solo i robot rispondessero ai comandi...}
{338}{}{Lo so, sono un fallimento totale.}
{339}{}{Mi scuso profondamente per lo stato dei terreni.}
{340}{}{Se potessi fare qualcosa al riguardo, lo farei.}
{341}{}{Forse 10001 ha ragione. Forse dovremmo semplicemente distruggere tutto.}
