{100}{}{Vedi Dex.}
{101}{}{Vedi un uomo affascinante, impeccabilmente curato. Sotto una massa impressionante di capelli lucidi di brillantina, i suoi occhi
 brillano di intensita'... o forse di follia.}
{200}{}{[Mentre ti avvicini alla camera criogenica, vedi un uomo nudo e attraente disteso sul pavimento. Porta
 le ginocchia al petto e le abbraccia. Rimane li' per alcuni istanti, fissando il vuoto mentre il suo corpo trema
 e i denti battono. Gradualmente, sembra calmarsi.]}
{201}{}{Uh, ciao?}
{210}{}{[Scatta con la testa verso di te e balza in piedi. Ti osserva intensamente, poi guarda attorno come un
 animale in trappola. Quando i suoi occhi tornano su di te, si addolciscono, e si rilassa mentre i ricordi gli tornano
 alla mente. Cambia rapidamente atteggiamento, mostrando una calma sicura nonostante sia nudo.] Non ti riconosco, amico.
 Non ti dispiace se mi vesto, vero?}
{211}{}{Immagino non ci sia nulla di male-}
{212}{}{Beh, io—}
{220}{}{Certo che non ti dispiace. Grazie, amico. [Ti passa accanto e apre un armadietto vicino. Si veste con calma
 con un abito elegante, poi infila in tasca il contenuto dell'armadietto. Con un pettinino, inizia a sistemare e modellare
 i suoi capelli scuri e lucidi con la precisione rapida di un professionista.] Allora, dov'e' il dottore? }
{221}{}{Il dottore? Oh, probabilmente e' qui da qualche parte. Anzi, credo stia arrivando proprio ora, quindi me ne vado
 e vi lascio parlare. Ciao!}
{222}{}{Potrebbe sorprenderti, ma sei stato congelato per moltissimo tempo. Chiunque fosse "il dottore", ormai e' morto
 da un pezzo. Se era un tuo amico, mi dispiace.}
{223}{}{Non voglio sconvolgerti, ma sei stato nel ghiaccio per *davvero* tanto tempo. Sono abbastanza sicuro che il tuo amico,
 "il dottore", sia morto da molto ormai.}
{224}{}{Ascolta, belloccio. Non ho scongelato il tuo culo psicotico per rispondere alle tue domande e guardarti mentre ti sistemi.
 Ti lascio vivere solo finche' mi dici qualcosa di utile. Quindi inizia a parlare. Piu' mi dici, piu' a lungo vivi.}
{230}{}{[La sua calma svanisce e gli occhi si infiammano di rabbia.] Pensi di poter intimidire ME? Hai la piu' vaga
 FOTTUTA idea di chi stai parlando? Vieni qui e ti faccio vedere di cosa sono capace!}
{231}{}{[Fatto.]}
{240}{}{[Dex ti sorride, mostrando una dentatura perfetta—frutto della odontoiatria prebellica, che ti appare strana
 nella sua simmetria bianco perlacea.] Il dottore, amico mio? [Alza un sopracciglio.] Non sai chi sono, vero?}
{241}{}{Uh, non proprio. Ho vagato un po' per questa strana struttura, armeggiando qua e la', e per caso ti ho scongelato.
 Perche' eri congelato li' dentro, comunque?}
{242}{}{Beh, secondo quel computer, tu sei Dex, un assassino narcisista e sociopatico di prima del grande silenzio.
 Ti ho scongelato solo per poterti abbattere come il cane malato che sei.}
{243}{}{Uh, non proprio. Sono sicuro che tu sia un tipo perfettamente normale congelato per motivi perfettamente normali e non malvagi. Diavolo, che ne so io? Ho vagato per questa strana struttura, armeggiando qua e la', e per caso ti ho scongelato.}
{250}{}{[Dex si guarda di nuovo attorno e fischia.] Questo posto e' davvero andato a puttane. Quanto hai detto che e' passato?}
{251}{}{Sono passati piu' di centocinquant'anni da quando il Grande Silenzio ha posto fine agli Antichi... *la tua* gente.}
{260}{}{Grande Silenzio? Gli Antichi? Perche' non risparmi queste stronzate criptiche e mi dici semplicemente cosa e' successo?}
{261}{}{Il Grande Silenzio e' come la mia gente chiama la fine del tuo mondo. Quando i grandi fuochi caddero dal cielo e bruciarono la terra. Scoprirai che il mondo non e' piu' nulla come quello che conoscevi.}
{270}{}{Ma va'? Quindi hanno davvero sganciato le bombe, eh? Immagino che il progetto dei vault non fosse solo un enorme spreco
 dei soldi dei contribuenti, dopotutto.}
{271}{}{Aspetta. Conosci i sacri Vault?}
{280}{}{Conoscerli? Diavolo, vivevo proprio accanto al vault di Chicago. Ho persino visto quando hanno finito di costruirlo.
 Poi ovviamente hanno iniziato con quelle maledette esercitazioni... [Si ferma e ti guarda divertito.] Te la stai bevendo tutta,
 vero?}
{281}{}{DIMMI DI PIU' DEI VAULT!}
{282}{}{Vedi, sono stato scelto dalla mia gente per cercare un Vault. Li', spero di recuperare un G.E.C.K. e usare il suo potere
 per salvare il mio villaggio dalla distruzione. Qualsiasi cosa tu possa dirmi sui Vault potrebbe aiutarmi nella mia missione.}
{283}{}{Vedi, ero stato scelto dalla mia gente per cercare un Vault. Dopo aver rischiato la vita in innumerevoli avventure,
 alla fine ho scoperto il Sacro 13. Tuttavia, sono curioso di sapere cos'altro potresti conoscere su questi posti.}
{290}{}{Ti diro' una cosa, amico. Tu hai bisogno di aiuto per trovare questi Vault, e io ho bisogno di qualcuno che mi faccia
 da guida, per cosi' dire, in questo tuo mondo impazzito. Allora che ne dici... partner?}
{291}{}{Hmm, la tua conoscenza degli Antichi potrebbe essermi utile... Ma, beh, sinceramente, ho letto di te
 in quel computer laggiu', e non sono sicuro che tu sia il tipo di persona con cui vorrei viaggiare.}
{292}{}{Non ho davvero il tempo di "farti da guida". Sono sicuro che te la caverai benissimo da solo, "amico".}
{293}{}{Direi che abbiamo un accordo... socio.}
{294}{}{Non credo di avere molta voglia di andare in giro per la zona contaminata con un assassino psicotico. Quindi te la
 caverai da solo, "amico". Non preoccuparti, sono sicuro che andra' tutto bene. [Sogghigna.]}
{300}{}{Ehi, fermati un attimo. Fammi indovinare, hai letto che ero una specie di assassino folle, giusto? Beh amico, ho due
 parole per te: Stron. Zate. Non credere a una sola parola.}
{301}{}{Ma non ha senso, perche' dovrebbero mentire su di te?}
{302}{}{L'unica stronzata qui in giro e' quella che esce dalla tua bocca, e credo sia ora di farti tacere per sempre.}
{310}{}{Ehi, so che non sembra avere molto senso, ma hai guardato questo posto? Qui non c'e' molto che abbia senso.
 Chissa' cosa passa nelle menti bacate di questi scienziati. }
{311}{}{Hmm... su questo hai ragione. Non dico che ti creda... ma suppongo di poterti almeno ascoltare.}
{312}{}{Sì, davvero. Continua...}
{320}{}{Ok, vedi, fa tutto parte dei loro "esperimenti". Quei fottuti dottori stavano facendo dei test sulla
 "natura del male umano" o qualche altra stronzata. Mi iniettavano i ricordi di un maniaco per vedere come
 avrebbero influenzato la personalita' di una persona normale. Almeno, questo e' quello che sono riuscito a capire.}
{321}{}{Beh... se e' vero, e' terribile. Ma perche' hanno scelto proprio te come cavia, all'inizio?}
{322}{}{Cavolo, amico, e' davvero una merda. Comunque, ormai e' tutto passato. Quegli stronzi di scienziati sono morti da un pezzo
 e non potranno piu' tormentarti. Vieni con me e ce ne andiamo da questo posto.}
{330}{}{Heh, vedi, e' questo il bello. *Sono stato io* ad andare *da loro*. Risposi a un annuncio in cui dicevano che avrebbero pagato
 un sacco di soldi per cavie sane. Avevo bisogno di soldi e... beh, si e' rivelato il peggior errore della mia vita.
 Non posso nemmeno iniziare a raccontarti gli orrori che mi hanno fatto. [Gli occhi gli brillano di lacrime mentre ricorda.
 Sospira profondamente e se le asciuga.] Comunque, grazie a te, amico, sono finalmente libero da quell'incubo.}
{331}{}{Uh. Beh, sono contento di aver potuto aiutare... credo.}
{332}{}{In realta', stronzo, il tuo incubo e' appena iniziato, perche' non credo a una sola parola di quello che hai detto.}
{340}{}{Allora che ne dici, amico? Facciamo squadra? Non solo sembrerai piu' figo stando con me, ma so cavarmela in uno scontro.
 Diavolo, potrei anche andare da solo, ma non ho idea di che razza di follie ci siano la' fuori adesso.
 Per quel che ne so, il primo albero su cui piscio potrebbe aprire la bocca e staccarmi il cazzo a morsi.}
{341}{}{D'accordo, puoi viaggiare con me, ma ti terro' d'occhio. Al primo segno che stai per fare una cazzata, ti stendo.}
{342}{}{Certo, suppongo che possiamo fare squadra. Benvenuto nel gruppo, Dex.}
{343}{}{Era una dannata bella storia, e non sei nemmeno un cattivo attore, il che ti rende ancora piu' pericoloso. Credo che faro'
 un favore alle Terre Desolate e ti elimino prima che tu possa fare altro danno.}
{350}{}{[Il sorriso di Dex vacilla e i suoi occhi si fanno assenti. Dopo un momento, inizia a parlare senza incrociare il tuo sguardo.]
 Ero uno dei loro malati esperimenti. Mi hanno fatto... cose terribili. [Scuote la testa, poi ti guarda con un sorriso rinnovato.]
 Preferirei non parlarne, sai? Comunque mi chiamo Dex.}
{351}{}{Mi dispiace sentirlo, Dex. Comunque ormai e' tutto nel passato. Nel passato, *vero* passato lontano.}
{352}{}{Senti, Dex, potrei anche aiutarti, ma vorrei sapere con chi ho a che fare. Che cosa ti hanno fatto esattamente?}
{360}{}{[Dex da' un altra occhiata alla stanza e fischia.] Non scherzi. Questo posto e' proprio andato a puttane. Quanto hai detto che e' passato?}
{370}{}{Va bene, devi proprio saperlo? D accordo. In pratica, quei fottuti medici pazzi stavano facendo una specie di test sulla "natura del male umano" o qualche stronzata del genere.
 Mi hanno iniettato i ricordi di un maniaco per vedere come avrebbe influenzato la personalita' di un bravo cittadino rispettoso della legge come me. Almeno, e' la spiegazione migliore che sono riuscito a darmi.}
{371}{}{Capisco. Quindi, come *ti* ha influenzato? }
{372}{}{Non lo so, mi ha dato qualche incubo, va bene? Senti, sono stato congelato per chissa' quanto tempo, e non sono dell'umore per un fottuto interrogatorio.
 Sei quasi peggio del Doc... Hai detto che e' morto? Quanto tempo sono rimasto fuori comunque? Questo posto sembra una merda.}
{400}{}{[Mentre ti avvicini alla camera criogenica, vedi un uomo nudo e attraente disteso sul pavimento. Porta le
 ginocchia al petto e le stringe con le braccia. Rimane li' per diversi istanti, fissando il vuoto mentre il suo corpo trema
 e i denti battono. Gradualmente, sembra calmarsi.]}
{401}{}{Uh, ciao?}
{410}{}{[Scatta con la testa verso di te e balza in piedi. Ti osserva con attenzione, poi si guarda intorno come un
 animale in trappola. Quando i suoi occhi tornano su di te, si addolciscono, e si rilassa mentre i ricordi tornano a fiume.
 Cambia rapidamente atteggiamento, ostentando una fredda sicurezza, nonostante la nudita'.] Ehi bambola, so di essere uno spettacolo
 niente male, ma qui dentro fa un po freddo. Ti dispiace se mi vesto?}
{411}{}{Immagino non ci sia nulla di male-}
{412}{}{Beh, io—}
{420}{}{Certo che non ti dispiace. Grazie, tesoro. [Ti passa accanto, dandoti una leggera pacca sul sedere, e apre un armadietto vicino.
 Si veste con noncuranza con un completo tagliato su misura, poi infila in tasca il contenuto dell armadietto. Con un pettinino da tasca,
 inizia a sistemare e modellare i suoi capelli scuri impomatati con la rapidita' precisa di un vero professionista.] Non credo di averti
 mai vista da queste parti, bambola, e dubito che dimenticherei una faccia come la tua. Mi chiamo Dex, ma sono sicuro che lo sai gia'. Posso sapere il tuo?}
{421}{}{Sono }
{422}{}{. Ma sappi che ho una regola ferrea: non esco con uomini strani che scongelo io. Visto che sei rimasto sul ghiaccio per l'ultimo secolo e mezzo, faro' finta che la tua mano abbia avuto uno spasmo e mi abbia dato uno schiaffo al culo per sbaglio. Ma se succede di nuovo, ti strappo il cazzo. Chiaro?}
{423}{}{Il mio nome e' }
{424}{}{. Piacere di conoscerti, Dex. Non riesco a immaginare cosa significhi svegliarsi dopo essere stato congelato per oltre centocinquant anni.}
{425}{}{Si', eccome se mi dispiace, fottuto schifoso. Ti ho scongelato solo per abbatterti come il cane malato che sei.}
{426}{}{Lascia perdere i nomi. Che ne dici di toglierti di nuovo quei vestiti e mostrarmi di che pasta sono fatti gli uomini del pre guerra.}
{430}{}{[Sorride e inizia a spogliarsi.] Sei il mio tipo, ragazza. Preparati a fare esperienza di Dex, il Duca del Sesso.}
{431}{}{[Continua]}
{440}{}{[Dopo un intensa sessione d'amore sul pavimento della camera, crollate entrambi per la stanchezza. Dex
 tiene un piccolo oggetto vicino alla tua bocca.] Urla per lei, piccola. [Proprio quando capisci che e' un orecchio umano mozzato, senti una lama trapassarti il petto. Urli mentre la lama viene estratta e affondata di nuovo...]}
{441}{}{[Fine]}
{450}{}{Ehi, ehi, ehi. Un momento, tesoro. Hai appena detto centocinquant'anni? [Scuote la testa incredulo.] E' fottutamente incredibile. [Controlla il suo riflesso.] Pero' devi ammetterlo, per la mia eta' sono dannatamente in forma. [Ti sorride, mostrando una dentatura perfetta - frutto dell'odontoiatria pre guerra che ti sembra strana in tutta la sua simmetria bianco perla.]}
{451}{}{Certo, magari qualche ragazza potrebbe trovarti attraente, ma faccio fatica a ignorare il fatto che sei uno psicopatico assassino a sangue freddo.}
{452}{}{Si', sei molto attraente, ma sinceramente sono un po' nervosa a parlarti dopo quello che ho letto su di te, che sei uno psicopatico assassino.}
{453}{}{Va bene, questo e' disgustoso. Vediamo quanto sarai affascinante dopo che ti avro' fatto un paio di buchi in faccia.}
{454}{}{Niente male per un uomo del ghiaccio. Perche' ti avevano congelato li' dentro, comunque?}
{455}{}{Eh, non sei il mio tipo. Comunque, perche' ti avevano congelato li' dentro?}
{456}{}{Va bene, questo e' disgustoso. Vediamo quanto sarai affascinante dopo che ti avro' fatto un paio di buchi in faccia.}
{460}{}{Ok, da dove tiri fuori questa stronzata che sarei uno "psicopatico assassino"?}
{461}{}{Non provare a prendermi per il culo. Ho letto di te su quel computer.}
{462}{}{Quel computer laggiu' aveva una specie di biografia su di te, e c'erano dentro cose piuttosto terribili.}
{463}{}{Lo percepisco. Emanì questa sensazione.}
{464}{}{Non provare a prendermi per il culo. Conosco quelli come te.}
{470}{}{Ah, ora ha senso. Senti, non preoccuparti per quello, non e' come pensi. Ti spiego tutto tra un
 secondo. Ma prima di tutto, ti dispiace dirmi che diavolo e' successo da quando mi hanno messo sul ghiaccio? Voglio dire, questo
 posto e' andato a puttane, e tu sembri uscita da una specie di racconto d'avventura fantascientifico.}
{471}{}{Sono passati piu' di centocinquant'anni da quando il Grande Silenzio ha posto fine agli Antichi... *la tua* gente.}
{475}{}{Grande Silenzio? Gli Antichi? Perche' non risparmi queste stronzate criptiche e mi dici semplicemente cosa e' successo?}
{476}{}{Il Grande Silenzio e' come il mio popolo chiama la fine del tuo mondo. Quando i grandi fuochi piovvero dal cielo e bruciarono la terra. Scoprirai che il mondo non e' affatto come quello che conoscevi. }
{480}{}{Non mi dire, quindi hanno davvero sganciato le bombe, eh? Immagino che il progetto Vault non fosse solo un enorme spreco dei soldi dei contribuenti, dopotutto.}
{481}{}{Aspetta. Conosci i sacri Vault?}
{490}{}{Conoscerle? Diavolo, vivevo proprio accanto al Vault di Chicago. Ho perfino visto finire di costruire quell'affare.
 Poi ovviamente hanno iniziato con quelle dannate esercitazioni... [Si ferma e ti guarda divertito.] Ti stai proprio bevendo
 tutto questo, vero, tesoro?}
{491}{}{DIMMI DI PIU' DEI VAULT!}
{492}{}{Vedi, sono stato scelto dalla mia gente per cercare un Vault. Li', spero di recuperare un G.E.C.K. e usare il suo potere
 per salvare il mio villaggio dalla distruzione. Qualsiasi cosa tu possa dirmi sui Vault potrebbe aiutarmi nella mia missione.}
{493}{}{Vedi, il mio popolo mi aveva scelto per cercare un Vault. Ho rischiato la vita in diverse occasioni per
 trovare questo Sacro Vault e alla fine ci sono riuscita. Sono curiosa di sapere cos'altro sai di questi luoghi.}
{500}{}{Ti dico una cosa, tesoro. Tu hai bisogno di aiuto per trovare questi Vault, e io ho bisogno di qualcuno che mi insegni come muovermi, per cosi' dire, in questo tuo mondo folle. Allora che ne dici... partner?}
{501}{}{Direi che abbiamo un accordo... socio.}
{502}{}{Be', la tua conoscenza degli Antichi potrebbe rivelarsi molto utile per me... ma, sai, c'e' tutta quella faccenda dello psicopatico assassino...}
{503}{}{Non credo di avere tanta voglia di andarmene in giro per le Terre Desolate con uno psicopatico assassino. Quindi sei per conto tuo,
 "tesoro". Non preoccuparti, sono sicura che te la caverai benissimo. [risatina.]}
{510}{}{Ehi, come ti ho detto, posso spiegare. Tutto quello che hai letto su di me era una completa stronzata. Non crederci nemmeno per una parola.}
{511}{}{Ehi, come ti ho detto, posso spiegare. Queste vibrazioni malvagie che percepisci da me sono il risultato degli scienziati che
 hanno sperimentato su di me.}
{512}{}{Ma non ha alcun senso. Che cosa ti hanno fatto?}
{513}{}{Stronzate. Credo sia ora di farti tacere per sempre.}
{514}{}{Ma non ha senso, perche' dovrebbero mentire su di te?}
{515}{}{L'unica stronzata qui dentro e' quella che ti esce dalla bocca e credo sia ora di farti tacere per sempre.}
{520}{}{Ehi, lo so che non sembra avere molto senso, ma ti sei guardata intorno? Qui dentro non c'e' molto di sensato. Chi puo' sapere cosa passa per le menti fottute di questi scienziati.}
{521}{}{Hmm... su questo hai ragione. Non sto dicendo che ti credo... ma suppongo di poterti almeno ascoltare.}
{522}{}{Sì, davvero. Continua...}
{530}{}{Va bene, vedi, fa tutto parte dei loro "esperimenti". Quei fottuti medici pazzi stavano facendo una specie di test
 sulla "natura del male umano" o qualche stronzata del genere. Mi iniettavano i ricordi di un maniaco, per vedere come
 avrebbe influenzato la personalita' di una persona normale. Almeno, e' la spiegazione migliore che sono riuscito a darmi.}
{531}{}{Beh... se e' vero, e' terribile. Ma perche' hanno scelto proprio te come cavia, all'inizio?}
{532}{}{Oh, poverino. Ormai e' tutto nel passato. Quegli uomini terribili sono morti da tempo e non potranno piu'
 farti del male. Vieni con me e ce ne andremo da questo posto.}
{540}{}{Eh, vedi, e' proprio questa la cosa divertente. *Io* sono andato da *loro*. Ho risposto a un annuncio in cui dicevano che avrebbero pagato
 un sacco di soldi per soggetti sani su cui fare test. Avevo bisogno di soldi e, be', si e' rivelato il peggior errore della mia vita.
 Non posso nemmeno iniziare a descriverti gli orrori a cui mi hanno sottoposto. [I suoi occhi si velano di lacrime mentre ripensa. Sospira
 profondamente e si asciuga le lacrime.] Comunque, grazie a te, }
{541}{}{Sono finalmente libero da quell'incubo.}
{542}{}{Uh. Beh, sono contento di aver potuto aiutare... credo.}
{543}{}{In realta', stronzo, il tuo incubo e' appena iniziato, perche' non credo a una sola parola di quello che hai detto.}
{550}{}{Allora che ne dici, tesoro? Facciamo squadra? Non solo porto in dote il mio aspetto irresistibile, ma so
 cavarmela in uno scontro. Diavolo, potrei anche andare da solo, ma non ho la minima idea di che razza di follia
 si nasconda la' fuori adesso. Per quanto ne so, il primo albero su cui piscio potrebbe aprire la bocca e staccarmi il cazzo a morsi.}
{551}{}{Va bene, puoi viaggiare con me, ma ti terro' d'occhio. Nel momento stesso in cui anche solo pensi
 di uscire dai ranghi, ti abbatto. }
{552}{}{Certo, suppongo che possiamo fare squadra. Benvenuto nel gruppo, Dex.}
{553}{}{Era una dannata bella storia, e non sei nemmeno un cattivo attore, il che ti rende ancora piu' pericoloso. Credo che faro'
 un favore alle Terre Desolate e ti elimino prima che tu possa fare altro danno.}
{554}{}{Direi che abbiamo un accordo... socio. }
{555}{}{Be', la tua conoscenza degli Antichi potrebbe rivelarsi molto utile... suppongo che abbiamo un accordo.}
{556}{}{Non ho davvero tempo di "insegnarti come muoverti". Sono sicura che te la caverai benissimo da sola, "tesoro".}
{560}{}{[Il sorriso di Dex vacilla e i suoi occhi si fanno assenti. Dopo un momento, inizia a parlare senza incrociare il tuo sguardo.]
 Ero uno dei loro malati esperimenti. Mi hanno fatto... cose terribili. [Scuote la testa, poi ti guarda con un sorriso rinnovato.]
 Comunque, preferirei di gran lunga parlare di te, tesoro.}
{561}{}{Oh, be', vediamo... Sono nata e cresciuta nel villaggio di Arroyo. Mia madre e' l'anziana del villaggio, e siamo discendenti diretti del leggendario abitante del Vault--}
{562}{}{Senti, Dex, potrei anche aiutarti, ma vorrei sapere con chi ho a che fare. Che cosa ti hanno fatto esattamente?}
{570}{}{Wow, davvero interessante, tesoro, e non vedo l'ora di sentire altro su di te. Davvero. Ma prima di tutto, che ne dici di spiegarmi che diavolo e' successo da quando mi hanno messo sul ghiaccio.
 Voglio dire, questo posto e' andato a puttane, e tu sembri uscita da una specie di racconto d'avventura fantascientifico.}
{580}{}{Va bene, devi proprio saperlo? D accordo. In pratica, quei fottuti medici pazzi stavano facendo una specie di test sulla "natura del male umano" o qualche stronzata del genere.
 Mi hanno iniettato i ricordi di un maniaco per vedere come avrebbe influenzato la personalita' di un bravo cittadino rispettoso della legge come me. Almeno, e' la spiegazione migliore che sono riuscito a darmi.}
{581}{}{Capisco. Quindi, come *ti* ha influenzato?}
{582}{}{Non lo so, mi ha dato qualche incubo, va bene? Senti, tesoro, ne ho passate tante e non sono dell'umore per un fottuto interrogatorio adesso.
 Ho risposto alle tue domande, ora che ne dici di spiegarmi che diavolo e' successo da quando mi hanno messo sul ghiaccio. Voglio dire, questo posto e' andato a puttane, e tu sembri uscita da una specie di racconto d'avventura fantascientifico.}
{600}{}{[Mentre ti avvicini alla camera criogenica, vedi un uomo nudo e attraente disteso sul pavimento. Porta le ginocchia
 al petto e le stringe con le braccia. Rimane li' per diversi istanti, fissando il vuoto mentre il suo corpo trema e i
 denti battono. Gradualmente, sembra calmarsi.]}
{601}{}{Uh, ehi...}
{610}{}{[Scatta con la testa verso di te e balza in piedi. Ti osserva con attenzione, poi si guarda intorno come un animale in trappola.
 Quando i suoi occhi tornano su di te, si addolciscono, e si rilassa mentre i ricordi tornano a fiume. Cambia rapidamente
 atteggiamento, ostentando una fredda sicurezza, nonostante la nudita'.] Non ti riconosco, amico. Non ti dispiace se mi vesto, vero?}
{611}{}{Immagino non ci sia nulla di male-}
{612}{}{Beh, io—}
{620}{}{Certo che non ti dispiace. Grazie, amico. [Ti passa accanto e apre un armadietto vicino. Si veste con calma
 con un abito elegante, poi infila in tasca il contenuto dell'armadietto. Con un pettinino, inizia a sistemare e modellare
 i suoi capelli scuri e lucidi con la rapidita' di un vero professionista.] Allora, dov'e' il dottore? }
{621}{}{Chi lo sa. Ovunque sia, sara' morto da un pezzo. Vedi, sei rimasto a fare il ghiacciolo per DAVVERO tanto tempo.}
{622}{}{Ascolta, belloccio. Non ho scongelato il tuo culo psicotico per rispondere alle tue domande e guardarti mentre ti sistemi.
 Ti lascio vivere solo finche' mi dici qualcosa di utile. Quindi inizia a parlare. Piu' mi dici, piu' a lungo vivi.}
{630}{}{Ah si'? [Ti osserva incuriosito.] Non sembri esattamente uno di questo posto, amico, eppure hai deciso di liberarmi
 e vorrei sapere perche'. Suppongo tu sappia chi sono?}
{631}{}{Si', tu sei Dex, giusto? Se quello che ho letto su di te e' vero, allora sei proprio un maledetto figlio di puttana. Mi piace.}
{632}{}{Beh, secondo quel computer, tu sei Dex, un assassino narcisista e sociopatico di prima del grande silenzio.
 Ti ho scongelato solo per poterti abbattere come il cane malato che sei.}
{633}{}{Non ne ho idea, ma emani vibrazioni malvagie e approvo.}
{640}{}{[La sua calma svanisce e gli occhi si infiammano di rabbia.] Pensi di poter intimidire ME? Hai la piu' vaga
 FOTTUTA idea di chi stai parlando? Vieni qui e ti faccio vedere di cosa sono capace!}
{641}{}{[Fatto.]}
{650}{}{[Dex ti sorride, mostrando una dentatura perfetta — frutto della odontoiatria prebellica, che ti appare strana
 nella sua simmetria bianco perlacea.] Sapevo che c'era qualcosa che mi piaceva di te. Hai buon gusto. Non e' che per caso
 sei anche un fan di The King?}
{651}{}{Uh... [Sguardo vuoto.]}
{652}{}{Oh si', adoro quel... ehm, come lo hai chiamato, The King? Si', un grande fan.}
{660}{}{Lascia perdere, amico. [Dex si guarda di nuovo attorno e fischia.] Questo posto e' davvero andato a puttane.
 Quanto hai detto che e' passato?}
{661}{}{Sono passati piu' di centocinquant'anni da quando il Grande Silenzio ha posto fine agli Antichi... *la tua* gente.}
{665}{}{Grande Silenzio? Gli Antichi? Perche' non risparmi queste stronzate criptiche e mi dici semplicemente cosa e' successo?}
{666}{}{Il Grande Silenzio e' come la mia gente chiama la fine del tuo mondo. Quando i grandi fuochi caddero dal cielo e bruciarono la terra. Scoprirai che il mondo non e' piu' nulla come quello che conoscevi.}
{670}{}{Ma va'? Quindi hanno davvero sganciato le bombe, eh? Immagino che il progetto dei vault non fosse solo un enorme spreco
 dei soldi dei contribuenti, dopotutto.}
{671}{}{Aspetta. Conosci i Vault?}
{680}{}{Conoscerli? Diavolo, ho ucciso la mia prima prostituta non lontano da dove stavano costruendo il Vault di Chicago.
 Bei tempi quelli... [Si ferma e ti guarda divertito.] Te la stai bevendo tutta, vero?}
{681}{}{DIMMI DI PIU' DEI VAULT!}
{682}{}{Beh, dovrei cercare un Vault per la mia tribu'. Una volta trovato, dovrei recuperare un G.E.C.K. cosi' da usarne il potere
 per salvare il mio villaggio morente. Qualsiasi cosa tu possa dirmi sui Vault renderebbe il mio compito molto piu' semplice.}
{683}{}{Vedi, ero stato scelto dalla mia gente per cercare un Vault. Ho rischiato la vita piu' volte per trovare quel dannato
 Sacro Vault e alla fine ci sono riuscito. Sono curioso di sapere cos'altro potresti conoscere su questi posti.}
{690}{}{Ti diro' una cosa, amico. Tu hai bisogno di aiuto per trovare questi Vault, e io ho bisogno di qualcuno che mi faccia
 da guida, per cosi' dire, in questo tuo mondo impazzito. Allora che ne dici... partner?}
{691}{}{Diavolo, non serve nemmeno provarci. Sarei felice di averti con me solo per vedere di persona cosa sai fare.}
{692}{}{Non lo so, Dex. Mettiamo che ti lasci venire con me e che torniamo sani e salvi in un insediamento remoto.
 Una volta li', come faccio a sapere che non cercherai di tagliarmi la gola alla prima occasione?}
{700}{}{Posso dire che non sei un santo, quindi potrei farti la stessa domanda. Ma per risponderti, non ti ucciderei
 perche' mi metterei nei guai. Saro' sincero, }
{701}{}{, non me ne frega un cazzo di nessuno o di niente, tranne che di me stesso. Se il mondo e' messo cosi' male come dici,
 allora restare con te e' la mia migliore possibilita'. E' semplice.}
{702}{}{Va bene. Andiamo.}
{703}{}{Ti sto solo prendendo per il culo, Dex. Non ho mai avuto davvero intenzione di portarti con me. Pensavo solo di
 divertirmi un po' con te prima di sfondarti il cranio.}
{800}{}{[Mentre ti avvicini alla camera criogenica, vedi un uomo nudo e attraente disteso sul pavimento. Porta le ginocchia
 al petto e le stringe con le braccia. Rimane li' per diversi istanti, fissando il vuoto mentre il suo corpo trema e i
 denti battono. Gradualmente, sembra calmarsi.]}
{801}{}{Uh, ehi...}
{810}{}{[Scatta con la testa verso di te e balza in piedi. Ti osserva intensamente, poi guarda attorno come un animale
 in trappola. Quando i suoi occhi tornano su di te, si addolciscono e si rilassa mentre i ricordi gli tornano alla mente.
 Cambia rapidamente atteggiamento, mostrando una calma sicura nonostante sia nudo.] Ehi bambola, so di essere uno spettacolo,
 ma qui fa un po' freddo. Ti dispiace se mi vesto?}
{811}{}{Immagino non ci sia nulla di male-}
{812}{}{Beh, io—}
{820}{}{Certo che non ti dispiace. Grazie, bella. [Ti passa accanto, dandoti una pacca sul sedere, e apre un armadietto vicino.
 Si veste con calma con un abito elegante, poi infila in tasca il contenuto dell'armadietto. Con un pettinino, inizia a
 sistemare e modellare i suoi capelli scuri e lucidi con la rapidita' di un vero professionista.] Non credo di averti gia'
 vista in giro, bambola, e dubito che dimenticherei una faccia come la tua. Mi chiamo Dex, ma questo lo sai gia'. Posso
 chiederti il tuo?}
{821}{}{Sono }
{822}{}{. Ma sappi che ho una regola ferrea: non esco con uomini strani che scongelo io. Visto che sei rimasto sul ghiaccio per l'ultimo secolo e mezzo, faro' finta che la tua mano abbia avuto uno spasmo e mi abbia dato uno schiaffo al culo per sbaglio. Ma se succede di nuovo, ti strappo il cazzo. Chiaro?}
{823}{}{Il mio nome e' }
{824}{}{. Piacere di conoscerti, Dex. Non riesco a immaginare cosa significhi svegliarsi dopo essere stato congelato per piu'
 di centocinquant'anni.}
{825}{}{Si', eccome se mi dispiace, fottuto schifoso. Ti ho scongelato solo per abbatterti come il cane malato che sei.}
{826}{}{Lascia perdere i nomi. Che ne dici di toglierti di nuovo quei vestiti e mostrarmi di che pasta sono fatti gli uomini del pre guerra.}
{830}{}{[Sorride e inizia a spogliarsi.] Sei il mio tipo, ragazza. Preparati a fare esperienza di Dex, il Duca del Sesso.}
{831}{}{[Dopo un'intensa sessione amorosa sul pavimento della stanza, crollate entrambi esausti. Noti Dex che cerca furtivamente
 di raggiungere un coltello nascosto. Lo afferri rapidamente ai genitali.]}
{832}{}{Tocca quel coltello e ti trasformo nel Duca Senza Cazzo. Inoltre, perche' rovinare una bella cosa? Noi due potremmo
 divertirci cosi' tanto insieme.}
{833}{}{Io... credo di essermi innamorato. [Dex si e' unito al tuo gruppo.]}
{840}{}{Whoa, whoa, whoa. Aspetta un secondo, tesoro. Hai appena detto centocinquanta anni? [Scuote la testa incredulo.]
 E' in-cazzo-credibile. [Si guarda riflesso.] Ma devi ammettere che sono dannatamente in forma per la mia eta'. [Ti sorride, rivelando una serie di denti perfetti - prodotto della dentistica pre-guerra che ti appaiono strani in tutta la loro
 simmetria bianco perla.]}
{841}{}{Certo, alcune ragazze potrebbero pensare che tu sia un tipo attraente, ma sono sicura che siano un po' scoraggiate da tutta quella
 storia da psicopatico assassino che ti porti dietro.}
{842}{}{Va bene, questo e' disgustoso. Vediamo quanto sarai affascinante dopo che ti avro' fatto un paio di buchi in faccia.}
{843}{}{Certo, alcune ragazze potrebbero pensare che tu sia un tipo attraente, ma sono sicura che siano un po' scoraggiate dalle
 vibrazioni da psicopatico assassino che emani.}
{844}{}{Niente male per un uomo del ghiaccio. Perche' ti avevano congelato li' dentro, comunque?}
{845}{}{Eh, non sei il mio tipo. Comunque, perche' ti avevano congelato li' dentro?}
{846}{}{Va bene, questo e' disgustoso. Vediamo quanto sarai affascinante dopo che ti avro' fatto un paio di buchi in faccia.}
{850}{}{Be' di solito non vedono quel lato di me finche' non e' troppo tardi. Ma comunque... [Dex si guarda di nuovo intorno nella stanza e fischietta.]
 Questo posto e' davvero andato a rotoli. Allora cosa mi sono perso?}
{851}{}{Sono passati piu' di centocinquant'anni da quando il Grande Silenzio ha posto fine agli Antichi... *la tua* gente.}
{855}{}{Grande Silenzio? Gli Antichi? Perche' non risparmi queste stronzate criptiche e mi dici semplicemente cosa e' successo?}
{856}{}{Il Grande Silenzio e' quello che il mio popolo chiama la fine del tuo mondo. Quando i grandi fuochi piovvero dal cielo e bruciarono la terra.
 Scoprirai che il mondo non e' per niente come quello che conoscevi.}
{860}{}{Non mi dire, quindi hanno davvero sganciato le bombe, eh? Immagino che il progetto Vault non fosse solo un enorme spreco dei soldi dei contribuenti, dopotutto.}
{861}{}{Aspetta. Conosci i Vault?}
{870}{}{Se li conosco? Cavolo, ho ammazzato la mia prima puttana non lontano da dove stavano costruendo il Vault di Chicago. Erano bei tempi...
 [Si ferma e ti guarda divertito.] Stai bevendo tutto questo, vero?}
{871}{}{DIMMI DI PIU' DEI VAULT!}
{872}{}{Be', dovrei cercare un Vault per la mia tribu'. Una volta trovato, mi si aspetta che trovi un G.E.C.K. cosi'
 possiamo usare il suo potere per salvare il mio villaggio morente. Qualsiasi cosa tu possa dirmi sui Vault potrebbe rendere il mio lavoro molto piu' facile.}
{873}{}{Be', vedi, ero stato scelto dal mio popolo per cercare di trovare un Vault. Ho rischiato la vita in diverse occasioni per
 trovare quel dannato Santo Vault e alla fine ci sono riuscito. Sono curioso di sapere cos'altro potresti sapere di questi posti.}
{880}{}{Senti un po', tesoro. Tu hai bisogno di aiuto per trovare questi Vault, e io ho bisogno di qualcuno che mi mostri come funziona, per cosi' dire,
 in questo tuo mondo pazzo. Cosa ne dici... socio?}
{881}{}{Diavolo, non serve nemmeno provarci. Sarei felice di averti con me solo per vedere di persona cosa sai fare.}
{882}{}{Non so, Dex. Diciamo che ti lascio venire con me e arriviamo alla relativa sicurezza di un insediamento.
 Una volta la', come faccio a sapere che non cercherai di tagliarmi la gola alla prima occasione?}
{883}{}{Direi che abbiamo un accordo... socio.}
{884}{}{Be', la tua conoscenza degli Antichi potrebbe rivelarsi molto utile... suppongo che abbiamo un accordo.}
{885}{}{Non ho davvero tempo di "insegnarti come muoverti". Sono sicura che te la caverai benissimo da sola, "tesoro".}
{890}{}{Posso dire che nemmeno tu sei un santo, quindi potrei farti la stessa domanda. Ma per rispondere alla tua domanda, non ti ucciderei
 perche' mi danneggerebbe. Saro' onesto, }
{891}{}{, non me ne frega un cazzo di nessuno o di niente, tranne che di me stesso. Se il mondo e' messo cosi' male come dici,
 allora restare con te e' la mia migliore possibilita'. E' semplice.}
{892}{}{Va bene. Andiamo.}
{893}{}{Sto solo prendendo per il culo, Dex. Non ho mai avuto intenzione di portarti con me. Pensavo solo di divertirmi un po'
 con te prima di sfondati il cranio.}
{900}{}{Ci arriviamo tra un secondo. Ma prima di tutto, che ne dici di aggiornarmi su cosa diavolo e' successo da quando mi hanno messo in ghiaccio.
 Voglio dire, questo posto e' andato a rotoli, e sembri uscita da qualche racconto di avventura fantascientifica.}
{1000}{}{Quali sono le novità?}
{1001}{}{[Dex alza un sopracciglio verso di te.] Qualcosa che non va?}
{1002}{}{Parla con me.}
{1003}{}{[Dex sorride.] Cosa c'e', amico?}
{1004}{}{Ti serve qualcosa?}
{1005}{}{Cosa può fare Dex per te?}
{1010}{}{Quali sono le novità?}
{1011}{}{[Dex alza un sopracciglio verso di te.] Qualcosa che non va, tesoro?}
{1012}{}{Parla con me, baby.}
{1013}{}{[Dex sorride.] Cosa c'e', bambola?}
{1014}{}{Ti serve qualcosa? Qualsiasi cosa? [Dex sorride.]}
{1015}{}{Cosa può fare Dex per te, baby?}
{1100}{}{Sei pronto ad andare?}
{1101}{}{Allora, si parte o no?}
{1102}{}{Sei pronto? Ho una voglia matta di muovermi.}
{1103}{}{Quindi, hai capito che stai meglio con me, eh?}
{1104}{}{Andiamo? Non sono abituato ad aspettare gli altri.}
{1105}{}{Dai. Sono stato congelato per oltre centocinquanta anni. Non vedo l'ora di muovermi.}
{1106}{}{Sto iniziando a perdere la pazienza.}
{1110}{}{Sei pronto a portarmi con te?}
{1111}{}{Andiamo.}
{1112}{}{No, non ancora.}
{1200}{}{Cosa puoi dirmi sui Vault?}
{1201}{}{E ora, ricordi qualcosa che puoi dirmi sui Vault?}
{1202}{}{C'e' qualcosa di utile che puoi dirmi sul tempo prima del Grande Silenzio?}
{1210}{}{Be', vediamo... Eh. Sai cosa? La mia mente e' ancora un po' annebbiata su alcune cose. Dovrai chiedermelo piu' tardi.}
{1211}{}{Hmm. Va bene.}
{1220}{}{I vault... i vault... No, non ancora.}
{1221}{}{Hmm. Va bene.}
{1230}{}{Si', in realta' ricordo... Aspetta, lascia perdere, ho dimenticato.}
{1231}{}{Hmm. Va bene.}
{1240}{}{Be', vivevo vicino al Vault di Chicago. Ti aiuta?}
{1241}{}{Sai se aveva un G.E.C.K.?}
{1242}{}{Sono sicuro di sì. Sono abbastanza certo che li avessero tutti.}
{1243}{}{Bene, ora ci siamo. Puoi dirmi dove si trova questo Vault?}
{1244}{}{Nessun problema. E' a circa 2.000 miglia in quella direzione. [Dex indica verso est.]}
{1245}{}{Oh. Beh allora… lascia perdere.}
{1250}{}{C'era un uomo, piu' grande di qualsiasi altro, che chiamavamo "Il Re". Era un bell'uomo con uno stile impeccabile,
 capelli straordinari e una voce d'oro. Con un semplice movimento del bacino poteva ingravidare ogni donna a vista.
 Era venerato come un Dio dalla gente del mondo. Era mio padre.}
{1251}{}{Interessante...}
{1260}{}{C'erano degli immortali che vivevano segretamente tra noi. Dovevano combattersi a morte con le spade finche'
 ne rimaneva uno solo per reclamare "Il Premio".}
{1261}{}{Aspetta. Se erano immortali, come potevano uccidersi a vicenda?}
{1262}{}{Potevano essere uccisi solo mediante decapitazione. Quando un immortale decapitava un altro, veniva rilasciato un risveglio
 che trasferiva i poteri dell'immortale ucciso al vincitore.}
{1263}{}{Cosa intendi esattamente con “poteri”?}
{1264}{}{Ehm, poteri di combattimento? Poteri meccanici? Non lo so, era un po' vago.}
{1265}{}{Interessante...}
{1270}{}{C'erano queste lucertole giganti, alcune piu' grandi degli edifici, su cui la gente ci girava in giro. Le chiamavamo
 dinosauri, ed erano conosciuti come il migliore amico dell'uomo.}
{1271}{}{Wow, ne avevi uno?}
{1272}{}{Certo. Ho cavalcato un T-rex, la piu' figa di tutte le lucertole giganti. Solo che la mia era ancora piu' figa perche' aveva le ali. Praticamente, era un drago.}
{1273}{}{Interessante...}
{1280}{}{Nell'anno 2011, ebbe luogo il Risveglio, e creature magiche a lungo dormienti, come Orchi, Elfi, Troll e
 Nani tornarono nel mondo, insieme alla magia. La magia e la tecnologia si scontrarono poi in un oscuro mondo di guerra aziendale,
 combattuta nelle ombre delle sconfinate metropoli.}
{1281}{}{Wow, che fine hanno fatto le creature magiche?}
{1282}{}{Immagino che siano stati eliminati quando caddero le bombe. Tranne che sembra che ci siano ancora alcuni Nani, Troll
 e Zombi in giro.}
{1283}{}{Interessante...}
{1290}{}{C'era questa gigantesca lucertola verde chiamata Godzilla. Godzilla si alternava tra il terrorizzare il Giappone
 e salvarne le chiappe dagli invasori spaziali giganti. C'era un'altra lucertola gigantesca e violenta chiamata Tarrasque. Credo fossero cugini o qualcosa del genere.}
{1291}{}{Wow, che fine hanno fatto?}
{1292}{}{Godzilla e' stato eliminato da Ferris Bueller. Quanto al Tarrasque, avevamo un robot gigante che lo combatteva. Il robot,
 pilotato dal sottoscritto, ha colpito il Tarrasque cosi' forte che si e' spezzato in migliaia di piccoli Tarrasque che
 si sono dispersi per tutta la California.}
{1293}{}{Interessante...}
{1300}{}{La terra era piena di donne attraenti, e detenevo il record mondiale per il numero di partner sessuali che ho avuto.}
{1301}{}{Capisco. Sai, Dex, alcune di queste cose che mi stai raccontando sono un po'... esagerate. Ho questa strana sensazione
 che non sia tutto vero.}
{1302}{}{Ehi, eri VIVO tu a quei tempi? No, non lo eri. Allora chi e' l'esperto del pre-guerra qui? Fidati, e' tutto vero.
 Ma ehi, se non mi credi, ho finito di raccontarti storie per ora.}
{1303}{}{Eh. Peccato, perche' sono state cosi' utili finora.}
{1400}{}{Dimmi solo dove mi vuoi.}
{1401}{}{Dimmi solo dove mi vuoi, bellezza.}
{1402}{}{Nessun problema. Non voglio metterti a disagio. [Dex sorride.]}
{1403}{}{Certo. Se pensi di dovermi tenere d'occhio, per me va bene.}
{1404}{}{Certo. Capisco che e' difficile concentrarsi quando sono troppo vicino. [Dex sorride.]}
{1405}{}{[Dex alza un sopracciglio verso di te e ti fa l'occhiolino.]}
{1406}{}{Nessun problema.}
{1500}{}{Perche'? Non ti fidi di me con le armi? [Ride.] Certo, se ti mette la mente in pace.}
{1600}{}{Eh, certo. Ma solo per essere chiari, sai che mi piacciono le ragazze... vero?}
{1601}{}{Va bene. [Dex si toglie l'armatura e inizia a togliersi i vestiti. Si ferma quando ti vede fissarlo.]
 Mi stai mandando segnali contrastanti, bambola. A Dex non piace essere preso in giro. Solo l'armatura allora.}
{1700}{}{Be', posso fare cose meravigliose con i coltelli. E' come un'arte. C'e' qualcosa di molto speciale nel modo in cui
 una lama affetta la carne, capisci cosa intendo?}
{1701}{}{Ehm... si', certo. Cos'altro sai usare? Sentiti libero di essere meno inquietante questa volta.}
{1702}{}{Be', mio zio era uno di quei militari duri. Mi ha addestrato con pistole e mitra, e ho anche potuto giocare
 con alcuni prototipi di armi energetiche su cui stavano lavorando. Pensava che avrei seguito le sue orme e sarei diventato un
 burattino dello Zio Sam, ma io, ehm... Diciamo solo che ho preso una strada diversa.}
{1703}{}{Sembra a posto. Altro?}
{1704}{}{Sono noto per prendere a pugni qualche culo con il buon vecchio pugilato. Da adolescente, ho provato il Karate per
 un po', ma continuavano a riempirmi di tutta quella roba sull'essere piu' disciplinato, cosi' gli ho detto di andare a fanculo. Cos'altro hai bisogno di sapere?}
{1705}{}{Direi che e' tutto. Grazie.}
{1800}{}{Sono pronto all'azione.}
{1801}{}{Ho passato giorni migliori, ma posso farcela.}
{1802}{}{Non mi sento molto bene.}
{1803}{}{Credo che il Re mi stia chiamando. Vedo la luce...}
{1900}{}{Nessun problema. Ma ti sentirai molto meno figo senza di me in giro. Lo dico solo...}
{1901}{}{Certo. Ci vediamo dopo.}
{1902}{}{Certo, aspetto. Ma se non torni, iniziero' a cercarti, e non sara' piacevole
 quando ti trovero'.}
{1903}{}{Va bene, purche' tu non mi stia mollando per fare posto a qualche altro idiota. Perche' ti prometto che sono
 migliore di loro in ogni modo immaginabile.}
{1904}{}{Nessun problema.}
{1905}{}{Nessun problema, baby.}
{1906}{}{Va bene, purche' tu non mi stia mollando per fare posto a qualche altro idiota. Perche' ti prometto che sono
 migliore di loro in ogni modo immaginabile.}
{1907}{}{Ti sto facendo venire troppo caldo, eh? Capisco.}
{2000}{}{D'accordo, di che si tratta?}
{2001}{}{Senti, so che sono stato in ghiaccio per molto tempo, ma fidati, tutto e' in PERFETTO stato di funzionamento. Se vuoi,
 te lo dimostro qui, adesso. [Dex si ferma quando ti vede fissarlo] Oh, capisco, il mio *altro* equipaggiamento. Cosa vuoi sapere?}
{2010}{}{E' un po' affollato. Fammi sapere se si libera qualcosa.}
{2020}{}{Non mi sogno nemmeno di viaggiare con te. Sei brutto da far schifo.}
{2030}{}{Andiamo.}
{2031}{}{Era ora di rimetterci in marcia.}
{3000}{}{Allora, qual e' la tua storia?}
{3001}{}{Cosa, tipo la storia della mia vita? Senti, so di essere piuttosto affascinante, ma non voglio stare qui a parlare per sempre.
 La bocca mi si secchera' tutta e non c'e' molta acqua in giro - non e' proprio una bella situazione.
 Ma suppongo di potertela riassumere se vuoi davvero sapere... In realta' MI piace parlare di me stesso quindi lascio
 a te la scelta. Vuoi il riassunto rapido o la versione piu' dettagliata?}
{3002}{}{Dammi un riassunto veloce.}
{3003}{}{Sentiamo la versione dettagliata.}
{3004}{}{Lascia stare, ho perso interesse.}
{3010}{}{Va bene, fondamentalmente, da quando ero bambino mi piaceva uccidere le cose. Potrei parlare della mia infanzia e dei miei
 genitori di merda e cercare di analizzare perche' mi piace farlo, ma non ho bisogno di scuse. Lo faccio semplicemente perche' posso, e
 e' divertente. A sedici anni passavo le giornate come un popolare idolo del liceo, e le notti come uno squartatore delle
 giovani lavoratrici di Chicago.}
{3011}{}{Uh huh. Continua.}
{3012}{}{Poi un giorno ho beccato la mia ragazza a fare la bestia a due schiene con un altro. Li ho fatti a pezzi, ho dato fuoco
 al posto, poi me la sono filata da Chicago. Ho passato i dieci anni successivi a girare il paese, sedurre ragazze
 e poi farle a pezzi. Poi alla fine mi hanno beccato, e il mio processo mi ha reso una celebrità.}
{3013}{}{E poi cosa e' successo?}
{3014}{}{Poi una delle mie nuove fan, Alice, mi aiuta a scappare. Noi due ci lanciamo in tre settimane di massacri attraverso il paese
 prima di cadere infine in una sparatoria. Poi, per qualche ragione, Il Sistema decide di ricucirmi e sottopormi a tutti
 questi test. Ed e' cosi' che sono finito all'EPA dove mi hai trovato.}
{3015}{}{Grazie per la storia.}
{3020}{}{Vediamo.... Mia madre era una drogata e una puttana, e mio padre era un bastardo ubriacone e scorbutico. Fortunatamente, mio
 nonno era a posto per essere un vecchio. Mi ha introdotto alla musica del Re. Purtroppo, e' stato colpito dalla Nuova Peste
 quando avevo sette anni. Poi quando ne avevo dieci, ho guardato dall'armadio mentre mio padre picchiava mia madre a morte per aver dimenticato di dare da mangiare
 al nostro cane, Capitan Robeenie.}
{3021}{}{Ottimo inizio. Continua pure.}
{3022}{}{La str*** avrebbe dovuto ricordarsi di dar da mangiare al Capitano. Continua.}
{3023}{}{Cosi' hanno messo via mio padre e mi hanno spedito a vivere con mia zia e mio zio. Vedi, ero un piccolo diavolo,
 anche allora, e mio zio, essendo un tipo militare, pensava di riuscire a raddrizzarmi - trasformarmi in un
 soldatino ammazza-Rossi, proprio come il figlio che aveva perso. Ci ha provato con tutte le sue forze, ma ero un bastardo testardo.}
{3024}{}{Uh huh. Continua.}
{3025}{}{Comunque, ci siamo spostati molto e non e' stato fino al liceo che ci siamo finalmente stabiliti
 a Chicago. E' allora che ho preso l'abitudine di sgattaiolare fuori di notte e accoltellare le puttane. Avevo ucciso cose per tutto il tempo che
 potevo ricordare, ma sventrare le bestiole del quartiere non si paragonava alla cosa vera, capisci?}
{3026}{}{Bene.}
{3027}{}{Quindi le cose andavano abbastanza bene, per lo piu'. Voglio dire, odiavo da morire mio zio e mia zia, ma a scuola ero
 il Signor Popolare. Ogni ragazzo voleva essere mio amico e ogni ragazza che guardavo era disposta ad aprirsi per me. Tranne questa
 ragazza, Vicky. Lei richiedeva davvero un po' di lavoro. Sorprendente, lo so, ma alla fine l'ho convinta a cedermi e a diventare la mia ragazza.}
{3028}{}{E nel frattempo facevi il serial killer come secondo lavoro?}
{3029}{}{Non mi interessa della tua fidanzatina del liceo. Lascia perdere la storia.}
{3030}{}{Si'. [Dex sorride.] Erano bei tempi. Ero davvero felice, sai? Dopo che ci siamo diplomati, Vicky ed io ci siamo presi
 un nostro posticino insieme, e andava tutto alla grande. Ma quella str*** ha dovuto andare a rovinare tutto tradendomi alle spalle.}
{3031}{}{Come ha osato.}
{3032}{}{L'ho beccata sul fatto, e ho perso la testa. Le cose si sono fatte davvero brutali. Era stato un lavoro sloppy e non avrei mai potuto
 semplicemente coprirlo. Cosi' ho dato fuoco al posto e sono andato via. Ho viaggiato molto, ho fatto molte ragazze e
 ne ho lasciate la maggior parte morte. Non era una brutta vita, sai? Ci hanno messo dieci anni, ma la legge mi ha finalmente raggiunto.}
{3033}{}{Uh-oh. E poi cosa e' successo?}
{3034}{}{Poi mi hanno processato ed e' diventato un piccolo circo mediatico. Le ragazze adoravano perche' sono un gran bel tipo,
 e tutti gli altri adoravano perche' era una distrazione dalle notizie sulla Nuova Peste e dalla politica. Cosi' ho pensato di
 dargli un vero spettacolo.}
{3035}{}{Cosa hai fatto?}
{3036}{}{Be' a quel punto avevo fatto un sacco di fan, ma ce n'era una in particolare, una vera bambola di nome Alice. Diceva
 che mi amava e avrebbe fatto qualsiasi cosa per me. Cosi' durante il mio processo, mi ha aiutato a farla franca. Era una scommessa azzardata,
 ma siamo stati abbastanza fortunati da riuscirci. Poi le cose sono diventate folli... Sei sicuro di non aver mai sentito nulla di tutto questo?}
{3037}{}{Sì sì, continua pure.}
{3038}{}{Non ne ho mai sentito parlare, e ora non voglio piu' sentirne. Lascia perdere, mi sto annoiando.}
{3039}{}{Be' ora che ero con Alice, era un po' difficile tornare ai miei vecchi modi di sedurre le donne e sventrarle.
 Invece, abbiamo iniziato a uccidere per il brivido chiunque fosse a portata di mano. Non importava quanto giovane o vecchio, eravamo
 assassini senza discriminazioni. Ma uccidendo cosi' imprudentemente, eravamo facili da tracciare. In tre settimane ci avevano
 in un angolo. Mi hanno abbattuto e Alice si e' fatta saltare le cervella.}
{3040}{}{Capisco. E poi?}
{3041}{}{Cosi' ero li', certo di stare per morire, ma poi questi agenti governativi sono intervenuti e mi hanno portato via. Mi hanno rimesso
 al cento percento, poi hanno iniziato a farmi questi test, cercando di capire cosa mi rende cosi' com'e'... Comunque,
 puoi immaginare il resto, e la gola mi si e' seccata dal parlare. Accidenti, speravo di evitarlo.}
{3042}{}{Grazie per la storia.}
{3100}{}{Hai qualche consiglio da darmi?}
{3101}{}{Consigli? Che tipo di consigli?}
{3102}{}{Beh, sono sicuro che te la cavi bene.}
{3103}{}{Oh, ho *tutti i tipi* di abilita'. Ma se stai cercando consigli... [Ti guarda, poi annuisce.] Va bene,
 che diavolo. Ti daro' qualche dritta che fara' strisciare le signore ai tuoi piedi. Ora, la prima cosa che devi fare e'...}
{3104}{}{Vuoi vedere le mie abilita'? Te le mostro in qualsiasi momento, tesoro. Ma se stai cercando consigli...
 [Ti guarda, poi annuisce.] Va bene, che diavolo. Ti daro' qualche dritta che fara' mangiare i ragazzi dalla tua mano.
 Ora, la prima cosa che devi fare e'...}
{3105}{}{Ecco fatto. Ora non andare a raccontare ad altri questi segreti del mestiere.}
{3106}{}{Grazie.}
{4000}{}{Mamma mia, quanto adoro il futuro post?nucleare.}
{4001}{}{Dai, diamoci dentro con un po' di violenza.}
{4002}{}{Troviamo altre giovani signore da, ehm, ammirare.}
{4003}{}{Andiamo a cercare altra conoscenza carnale.}
{4004}{}{Hai mai steso una ragazza su un letto e l'hai aperta? Te lo dico io, bellezza assoluta.}
{4005}{}{Ho davvero bisogno di tagliare qualcosa, presto...}
{4006}{}{Penseresti che un cadavere sia terribile a letto, ma ti sorprenderesti.}
{4007}{}{[cantando] Ho messo un'ascia in testa alla mia baby, finiro' in prigione... stava cosi' bene in rosso...[cantando]}
{4008}{}{[cantando] perche' sono il maaaleeeee, il mio secondo nome e', miseriaaa...[cantando]}
{4009}{}{Ti piace il mio vestito? Questa dolce creatura e' stata fatta a Grand Rapids, Michigan.}
{4010}{}{Allora... dove pensi che tengano il gel per capelli nelle Lande?}
{4011}{}{So che suona un po' schifoso, ma non sputare sulle ovaie fritte finche' non le hai provate.}
{4012}{}{[Tira fuori il pettine tascabile e si sistema i capelli.]}
{4020}{}{Ehi! Sto sanguinando come un dannato!}
{4021}{}{Oh cavolo, non sto affatto bene.}
{4022}{}{Portatemi da un dannato dottore!}
{4023}{}{Stai lì a guardarmi morire dissanguato o hai intenzione di fare qualcosa?}
{4030}{}{Mi sento un po' strano...}
{4031}{}{Ehi, mi sento un po' irradiato. Se non e' il tipo che concede superpoteri, allora saro' una furia.}
{4040}{}{Sai, sei davvero una cattiva influenza.}
{4041}{}{Cerco di stare lontano da questa roba. Ma se insisti...}
{4042}{}{Il mio corpo e' un tempio, ma immagino che per una volta non fara' male.}
{4043}{}{Se questo mi lascia danni permanenti, ti faccio a pezzi.}
{4045}{}{Ora mi sento molto meglio.}
{4046}{}{Molto meglio.}
{4050}{}{Ehi! Attento ai capelli.}
{4051}{}{Ehi, la perfezione non si affretta.}
{4060}{}{Non e' la stessa cosa quando il loro sangue e' ancora caldo, sai?}
{4061}{}{Spero che tu abbia preso appunti.}
{4062}{}{Le ragazze sono diventate piuttosto strane dalla fine del mondo... mi piace.}
{4063}{}{...ed e' per questo che le ragazze mi chiamavano "Dex, il Duca del Sesso".}
{4070}{}{Mi sento nauseato. Credo di essere avvelenato.}
{4071}{}{Ho voglia di vomitare le budella.}
{4080}{}{Non riesco a muovere questo arto. Ho bisogno di cure mediche.}
{4081}{}{Credo di aver perso la sensibilita' in questo arto. E' grave?}
{4090}{}{E' diventato tutto molto sfocato. Dove sono andati tutti?}
{4091}{}{Credo che mi stia uscendo sangue dagli occhi.}
{4100}{}{Allora, tatuaggi in faccia, eh? Immagino che se fossi brutto come naso-d'osso qui, vorrei coprirlo anch'io.}
{4101}{}{Ehi, tatuaggi-in-faccia. Sei il tipo cannibale? Forse potremmo scambiarci delle ricette o qualcosa del genere.}
{4102}{}{Ho la sensazione che il tuo amico Sulik qui non mi vada a genio piu' di tanto. Hai mai pensato di venderlo per qualche soldo?}
{4110}{}{Seriamente, cosa c'e' con il tipo pelato e trasandato? Lo tieni per pieta' o qualcosa del genere?}
{4111}{}{Allora Vic, ho sentito che hai una figlia in gamba. Dovresti presentarmela.}
{4120}{}{Miria, tesoro, dobbiamo davvero passare un po' di tempo da soli insieme.}
{4121}{}{Quindi immagino che ci diamo il turno con Miria, giusto?}
{4122}{}{[Fa l'occhiolino a Miria.]}
{4123}{}{[Sorride a Miria.]}
{4124}{}{Miria, hai bisogno di un uomo che sia alla tua altezza. Sai, uno come me.}
{4125}{}{[Brandisce il coltello verso Miria. Sorride.]}
{4130}{}{Dico che facciamo un buco in testa a Davin e lo rotoliamo in un fosso.}
{4131}{}{Diciamo, ipoteticamente, che a Davin in qualche modo viene tagliata la gola nel sonno stanotte. A nessuno importera', giusto?}
{4140}{}{Ehi Cassidy, dovresti davvero provare un po' di Psycho. Ho sentito che puo' persino far ricrescere i capelli.}
{4141}{}{Perche' non bevi un po' di piu', Cassidy? Sembra che ti abbia invecchiato cosi' bene.}
{4142}{}{E' patetico vedere qualcuno vecchio come Cassidy che cerca di aggrapparsi alla vita. Se fossi nei suoi panni,
 bacerei la canna di un fucile e la finirei li'.}
{4150}{}{Diciamo che molliamo il cadavere ambulante.}
{4151}{}{Va bene, questa barzelletta di portarsi dietro Lenny e' andata avanti un po' troppo ora, non credi?}
{4152}{}{Come diavolo dovrei rimorchiare le ragazze con Lenny sempre tra i piedi?}
{4160}{}{Allora, ehm, Marcus, quando torni ad essere il tranquillo fisico dai modi gentili?}
{4161}{}{Ehi Marcus, non dovresti essere da qualche parte a governare una citta'?}
{4170}{}{Tieni duro Myron, sono sicuro che prima o poi ti cadranno le palle.}
{4171}{}{Il nerdetto mi sta un po' rovinando lo stile.}
{4172}{}{Myron e' come un brufolo gigante, che aspetta solo di essere schiacciato.}
{4180}{}{Almeno Goris ha il buon senso di coprirsi.}
{4181}{}{Ottimo lavoro mimetizzarti, Goris. Sembri proprio un tipico mostro gobbo.}
{4200}{}{Sono curioso di vedere come sono le donne tribali.}
{4210}{}{Puttane... puttane ovunque. Adoro questo posto del cazzo.}
{4220}{}{Questo posto sembra proprio voler un po' di caos.}
{4230}{}{Ci sono troppi sbirri qui. Dico che ce la filiamo.}
{4240}{}{Ottimo, altri fenomeni da baraccone. Meglio non restare qui più del necessario.}
{4250}{}{Stiamo perdendo tempo qui. Le ragazze zombie non fanno per me. Di solito non mi piace che le ragazze sembrino morte fino a DOPO che ho finito con loro.}
{4260}{}{Perche' diavolo stiamo perdendo il nostro tempo qui? Sul serio?}
{4270}{}{Non penso di voler passare altro tempo in questa struttura di mia spontanea volonta'.}
{5000}{}{[Scatta la testa verso di te e balza in piedi. Mentre ti guarda, i suoi occhi si spalancano improvvisamente e inizia ad ansimare per l'aria.]}
{5001}{}{[FINE]}
{5002}{}{Oh, merda!}
